"""Throwaway CK3 scaffolding so the physical map can be loaded in game.

**Everything in this module is placeholder content that the ``titles-history``
lane replaces.**  It exists for one reason: CK3 will not boot a custom map
without a title layer over it, and a map that cannot be booted cannot be
checked.  Every file it writes carries a THROWAWAY banner.

Design notes and the evidence behind them are in ``docs/output_bootstrap.md``:

* ``descriptor.mod``, not ``.metadata/metadata.json`` — none of Atlantis,
  Elder Kings 2 or Godherja ships a metadata dir, and ck3-tiger cannot read one.
* ``replace_path`` replaces one directory and **not** its subdirectories, so
  ``map_data`` itself needs no replace_path (same-filename override is enough,
  the Elder Kings 2 / Godherja pattern) while
  ``map_data/geographical_regions`` does need one.
* one barony per province, named from the CK2 ``definition.csv`` name, because
  this lane is explicitly one CK3 province per CK2 province.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from .idmap import Ck3Province

THROWAWAY = (
    "# THROWAWAY SCAFFOLDING generated by ck2ck3 lane map-physical.\n"
    "# One barony per CK2 province, no real de-jure structure, no history.\n"
    "# The titles-history lane replaces this file wholesale. Do not build on it.\n"
)

#: directories our generated mod must replace rather than merge into vanilla.
#: `verified` from the ck3-tiger binary's own help text: "replace_path only
#: replaces the specific directory, not any directories below it".
REPLACE_PATHS = (
    "common/landed_titles",
    "history/characters",
    "history/cultures",
    "history/province_mapping",
    "history/provinces",
    "history/struggles",
    "history/titles",
    "history/wars",
    "map_data/geographical_regions",
)


def slugify(name: str, fallback: str) -> str:
    """CK3 title keys are ``[a-z0-9_]``; CK2 province names are free text."""
    s = name.lower()
    s = s.replace("'", "").replace("’", "")
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s or fallback


def unique_keys(provinces: Sequence[Ck3Province]) -> dict[int, str]:
    """CK3 province id -> unique slug, suffixed on collision."""
    out: dict[int, str] = {}
    used: dict[str, int] = {}
    for p in provinces:
        base = slugify(p.name, f"province_{p.id}")
        n = used.get(base, 0)
        used[base] = n + 1
        out[p.id] = base if n == 0 else f"{base}_{n + 1}"
    return out


@dataclass(frozen=True)
class BootstrapDefaults:
    """Vanilla ids used as placeholders so the game has something valid to load."""

    culture: str = "norse"
    religion: str = "asatru"
    faith: str = "asatru"
    holding: str = "castle_holding"


#: CK3 world-extent defines. NOT throwaway — a custom map size is wrong
#: without these, and the symptom is a silently misplaced coastline.
#:
#: `verified` in game/common/defines/00_defines.txt:74-77 (vanilla 9216x4608),
#: Elder Kings 2 common/defines/ek_defines.txt:34-37 (8256x5504) and Godherja
#: common/defines/00_defines.txt:79-82 (8192x4096):
#:   WORLD_EXTENTS_X = provinces.png width  - 1
#:   WORLD_EXTENTS_Z = provinces.png height - 1
#:   WORLD_EXTENTS_Y = vertical world extent in game units (50 vanilla, 51 both TCs)
#:   WATERLEVEL      = water surface in the same units (3 vanilla, 3.8 both TCs)
#:
#: and the 16-bit heightmap value of the water surface follows:
#:   water = WATERLEVEL / WORLD_EXTENTS_Y * 65535
#: vanilla 3/50*65535 = 3932, both TCs 3.8/51*65535 = 4883, which is exactly the
#: value measured off their coastlines (docs/formats_map.md §3).
WORLD_EXTENTS_Y = 51
WATERLEVEL = 3.8


def water_level_16bit(
    *, waterlevel: float = WATERLEVEL, extents_y: float = WORLD_EXTENTS_Y
) -> int:
    """The 16-bit ``heightmap.png`` value of the water surface."""
    return int(round(waterlevel / extents_y * 65535))


def render_defines(
    *,
    width: int,
    height: int,
    extents_y: float = WORLD_EXTENTS_Y,
    waterlevel: float = WATERLEVEL,
) -> str:
    """``common/defines/<prefix>_defines.txt`` — the map's world extents."""
    return (
        "# GENERATED by ck2ck3 (lane map-physical). Do not hand-edit.\n"
        "# World extents must match provinces.png or the coastline moves:\n"
        "#   WORLD_EXTENTS_X = width - 1, WORLD_EXTENTS_Z = height - 1.\n"
        f"# Water surface in heightmap.png is {water_level_16bit(waterlevel=waterlevel, extents_y=extents_y)}"
        f" = {waterlevel} / {extents_y} * 65535.\n"
        "NJominiMap = {\n"
        f"\tWORLD_EXTENTS_X = {width - 1}\n"
        f"\tWORLD_EXTENTS_Y = {extents_y}\n"
        f"\tWORLD_EXTENTS_Z = {height - 1}\n"
        f"\tWATERLEVEL = {waterlevel}\n"
        "}\n"
    )


# NOTE: descriptor.mod is NOT written here. The `descriptor` step owns it
# (docs/cli.md) and takes its replace_path list from `mod.replace_paths` in the
# CLI config, so REPLACE_PATHS below has to be mirrored there. The standalone
# entry point writes it via render_descriptor().


def render_descriptor(*, name: str, version: str, supported_version: str) -> str:
    """descriptor.mod, for the standalone entry point only."""
    out = [f'version="{version}"']
    out += [f'replace_path="{rel}"' for rel in REPLACE_PATHS]
    out += [
        "tags={",
        '\t"Total Conversion"',
        '\t"Map"',
        "}",
        f'name="{name}"',
        f'supported_version="{supported_version}"',
    ]
    return "\n".join(out) + "\n"



def render_landed_titles(
    provinces: Sequence[Ck3Province],
    keys: dict[int, str],
    *,
    empire_key: str = "e_placeholder",
    kingdom_key: str = "k_placeholder",
    duchy_key: str = "d_placeholder",
) -> tuple[str, int]:
    """One county per land province, one barony inside it, all under one kingdom.

    Grouping by the real CK2 duchies is deliberately *not* done here: the CK2
    duchy layer lives in ``common/landed_titles`` on the CK2 side and porting it
    is the titles-history lane's whole job.  A flat single-kingdom tree is the
    cheapest thing CK3 accepts, and it keeps this file obviously throwaway.
    """
    land = [p for p in provinces if not p.is_water and not p.is_impassable]
    out = [THROWAWAY, "", f"{empire_key} = {{", "\tcolor = { 120 120 160 }", ""]
    out += [f"\t{kingdom_key} = {{", "\t\tcolor = { 130 130 170 }", ""]
    out += [f"\t\t{duchy_key} = {{", "\t\t\tcolor = { 140 140 180 }", ""]
    for p in land:
        key = keys[p.id]
        out += [
            f"\t\t\tc_{key} = {{",
            "\t\t\t\tcolor = { %d %d %d }" % p.rgb,
            f"\t\t\t\tb_{key} = {{",
            "\t\t\t\t\tcolor = { %d %d %d }" % p.rgb,
            f"\t\t\t\t\tprovince = {p.id}",
            "\t\t\t\t}",
            "\t\t\t}",
        ]
    out += ["\t\t}", "\t}", "}"]
    return "\n".join(out) + "\n", len(land)


def render_province_history(
    provinces: Sequence[Ck3Province],
    defaults: BootstrapDefaults = BootstrapDefaults(),
) -> tuple[str, int]:
    """``history/provinces/<prefix>_provinces.txt``.

    CK3 needs a culture and a faith on every land province or the province is
    unsettled and the map shows holes.  Vanilla ids are used on purpose: the
    cultures-religions lane has not run, and inventing a culture here would
    break the no-invention rule.
    """
    land = [p for p in provinces if not p.is_water and not p.is_impassable]
    out = [
        THROWAWAY,
        f"# Placeholder culture/faith are the vanilla ids {defaults.culture!r} /"
        f" {defaults.faith!r}; the cultures-religions lane replaces them.",
        "",
    ]
    for p in land:
        out += [
            f"{p.id} = {{",
            f"\tculture = {defaults.culture}",
            f"\treligion = {defaults.faith}",
            f"\tholding = {defaults.holding}",
            "}",
        ]
    return "\n".join(out) + "\n", len(land)


def render_title_history(*, kingdom_key: str = "k_placeholder") -> str:
    """``history/titles/`` — empty is valid; the dir must exist for replace_path."""
    return THROWAWAY + f"# No title holders yet; {kingdom_key} starts unheld.\n"


#: replaced directories this lane fills with real content, so they get no banner
HAS_REAL_CONTENT = frozenset(
    {
        "common/landed_titles",
        "history/provinces",
        "history/titles",
        "map_data/geographical_regions",
    }
)


def render_empty_replacements(
    skip: frozenset[str] = HAS_REAL_CONTENT,
) -> dict[str, str]:
    """One banner file in each replaced directory so the dir is not empty.

    A ``replace_path`` on a directory that does not exist in the mod is what
    actually neutralises vanilla content, but an empty directory does not
    survive git, so each gets a comment-only file.
    """
    out: dict[str, str] = {}
    for rel in REPLACE_PATHS:
        if rel in skip:
            continue  # this lane writes real content there
        out[f"{rel}/zz_emptied_by_converter.txt"] = (
            THROWAWAY
            + f"# {rel} is replace_path'd so vanilla content here is dropped:\n"
            "# it references vanilla province ids that do not exist on this map.\n"
        )
    return out


def localisation_entries(
    provinces: Sequence[Ck3Province], keys: dict[int, str]
) -> dict[str, str]:
    """Localisation keys for the placeholder titles.

    Returned as a dict, not a file, so the caller writes them with
    ``ctx.write_loc`` -- which owns the UTF-8 BOM, the CRLF line endings and
    the ``l_english:`` first line that CK3 requires.
    """
    out: dict[str, str] = {}
    for p in provinces:
        if p.is_water or p.is_impassable:
            continue
        out[f"c_{keys[p.id]}"] = p.name
        out[f"b_{keys[p.id]}"] = p.name
    out["e_placeholder"] = "Converter Placeholder Empire"
    out["k_placeholder"] = "Converter Placeholder Kingdom"
    out["d_placeholder"] = "Converter Placeholder Duchy"
    return out
