"""``gfx/map/terrain/colormap.dds`` — the large-scale colour wash.

`docs/map_fidelity.md` §1.3/§4.3: CK3 samples this texture as a broad colour
tint *multiplied over the terrain materials*; ship none and the game shows
vanilla's own Europe colormap stretched across our canvas.

**Lane `map-colour` first shipped a resample of CK2's own
`map/terrain/colormap.dds`** (pixel-aligned with `provinces.bmp`). The
coordinator's in-game check found this wrong twice over
(`docs/step_map_paint.md` §9.6, `verified` by sampling both files): vanilla's
`colormap.dds` is a **near-neutral tint** (ocean 131,129,131, France land
148,125,106 — a tight band around grey, not saturated colour), while CK2's
`colormap.dds` is a **saturated satellite-style land painting** with no
sea/land distinction of its own (CK3 draws water over it) and its own
artistic geometry unrelated to our province layout — its arctic patch landed
on Waterdeep. `[map] colormap` shipped `false` until this was fixed.

**This lane (`colormap-fix`) replaces the resample with a measured tint per
CK3 terrain key**, calibrated against vanilla's own per-material colormap
means rather than guessed:

* `scripts/measure_vanilla_colormap_tints.py` pairs vanilla's own
  `gfx/map/terrain/detail_index.tga` (the material painted at each pixel,
  `ck2ck3.map.terrain_paint`) with `colormap.dds` (the tint at that same
  pixel — both `verified` 9216x4608, pixel-aligned) to measure the real mean
  tint vanilla itself uses for every material, plus the mean over water
  (vanilla's own `sea_zones`/`lakes` provinces). Output:
  `docs/evidence/vanilla_colormap_tints.csv`.
* `scripts/build_colormap_tints_csv.py` turns that into
  `mappings/colormap_tints.csv` — CK3 terrain key -> tint RGB — by looking up
  each key's **primary** material in `mappings/terrain_paint.csv` (the table
  the terrain-paint pass already uses, not a second hand-picked one) and
  taking that material's measured tint. A checked-in, human-editable table,
  regenerated by the script when either input changes.
* :func:`build_from_terrain` paints this raster directly from the same CK2
  terrain-code grid `ck2ck3.map.terrain_paint.build_layers` already uses (no
  second resize), overrides every `water_mask` pixel with the measured water
  tint, then blurs with a Gaussian sigma **measured** from vanilla's own
  colour autocorrelation length (`scripts/measure_vanilla_colormap_blur.py`,
  `docs/evidence/vanilla_colormap_blur.csv`) so terrain-key boundaries do not
  read as flat colour blocks the way vanilla's own geography-driven variation
  never does.

**Format decision, `verified` against two shipped, currently-loadable CK3
total conversions** rather than by guessing at vanilla's own format — this
part is unchanged by the tint rewrite, only the *content* of the array is new:

* Vanilla 1.19 ships `colormap.dds` at full province resolution (9216x4608),
  **DXT5** (BC3), 14 mip levels, 56.6 MB (`xxd` on the real game file: fourCC
  `DXT5`, `dwMipMapCount = 14`, `dwPitchOrLinearSize = 42,467,328` = exactly
  `9216*4608` — one byte/pixel average, the DXT5 rate).
* Elder Kings 2 and Godherja — both `verified` loadable total conversions —
  ship `colormap.dds` **uncompressed 32-bit BGRA (A8R8G8B8), at exactly
  one-quarter of their own province-map resolution**: EK2 2064x1376 for its
  8256x5504 canvas, Godherja 2048x1024 for its 8192x4096 canvas, alpha = 255
  everywhere (`verified`, sampled). Neither ships DXT5. Godherja's carries a
  full mip chain (12 levels to 1x1); EK2's does not.

This module follows the two real conversions, not vanilla's own bake: a BC3
(DXT5) encoder is more machinery than this repo has for one texture that is
explicitly "the large-scale colour wash" (`docs/map_fidelity.md` §4.3), not
per-pixel detail, and quarter resolution is what the format is *for*. Writing
uncompressed also sidesteps the one open question a BC3 path would add
(`docs/step_map_paint.md` §8.2 found only weak evidence CK3 loads `.dds` at
all for the sibling `detail_index`/`detail_intensity` pair — this file is a
different, `verified`-safe case because two shipped mods already do exactly
this with `colormap.dds`).
"""

from __future__ import annotations

import csv
import struct
from collections.abc import Callable, Sequence
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter

from .terrain import CK2_TO_CK3_TERRAIN as _CK2_TO_CK3_TERRAIN

#: where the engine looks
COLORMAP_PATH = "gfx/map/terrain/colormap.dds"

# DDSD_CAPS | HEIGHT | WIDTH | PIXELFORMAT | PITCH (uncompressed -> PITCH, not
# LINEARSIZE; `verified` against EK2/Godherja's own header byte 8: 0x0000100f)
_DDSD = 0x1 | 0x2 | 0x4 | 0x1000 | 0x8
_DDSD_MIPMAPCOUNT = 0x20000
_DDPF_ALPHAPIXELS = 0x1
_DDPF_RGB = 0x40
_DDSCAPS_TEXTURE = 0x1000
_DDSCAPS_COMPLEX = 0x8
_DDSCAPS_MIPMAP = 0x400000

#: A8R8G8B8 channel masks, `verified` byte-for-byte against both reference
#: mods' colormap.dds (offsets 92/96/100/104 of the header)
_R_MASK = 0x00FF0000
_G_MASK = 0x0000FF00
_B_MASK = 0x000000FF
_A_MASK = 0xFF000000


#: used when a CK3 terrain key has no row in mappings/colormap_tints.csv, or
#: the table itself is missing.
DEFAULT_TINT = (128, 128, 128)

TINT_CSV_HEADER = "ck3_terrain,tint_r,tint_g,tint_b"


def read_tint_map(path: str | Path) -> dict[str, tuple[int, int, int]]:
    """``mappings/colormap_tints.csv``: CK3 terrain key (or ``water``) -> RGB.

    Extra columns (``sample_count``, ``note``) are ignored; ``#`` comment
    lines are skipped like every other reader in this repo. A missing file
    returns ``{}``, so every key falls back to :data:`DEFAULT_TINT` rather
    than raising.
    """
    p = Path(path)
    if not p.exists():
        return {}
    with p.open("r", encoding="utf-8", newline="") as fh:
        lines = [line for line in fh if not line.lstrip().startswith("#")]
    out: dict[str, tuple[int, int, int]] = {}
    for row in csv.DictReader(lines):
        key = (row.get("ck3_terrain") or "").strip()
        if not key:
            continue
        try:
            out[key] = (
                int(row["tint_r"]),
                int(row["tint_g"]),
                int(row["tint_b"]),
            )
        except (KeyError, ValueError):
            continue
    return out


def build_from_terrain(
    codes: np.ndarray,
    code_names: Sequence[str],
    *,
    tint_map: dict[str, tuple[int, int, int]],
    water_mask: np.ndarray,
    mapping: dict[str, str] | None = None,
    default: str = "plains",
    blur_sigma: float = 9.0,
    warn: Callable[[str], None] = lambda _m: None,
) -> np.ndarray:
    """Paint a colour raster from the CK2 terrain-code grid + measured tints.

    ``codes``/``code_names`` are exactly ``ck2ck3.map.terrain_paint``'s own
    inputs (the CK2-category code grid at canvas resolution and its names,
    ``build.py``'s ``codes_tgt``/``code_names``) — the same per-pixel terrain
    classification the paint pass uses, not a second computation.
    ``water_mask`` (canvas resolution, boolean) is the map step's own
    land/water classification (``build.py``'s ``water_mask``, built from CK3
    province ids, not the CK2 terrain-category water codes) and overrides the
    terrain-key tint wherever it is true, matching the ``sea``/
    ``coastal_sea`` rows' own note in ``mappings/terrain_paint.csv`` that
    those keys exist only so a stray water pixel gets *some* code.

    ``blur_sigma`` (canvas pixels) is a Gaussian blur applied after painting,
    so per-terrain-key boundaries do not read as flat colour blocks the way
    vanilla's own geography-driven variation never does. The default (9) is
    `scripts/measure_vanilla_colormap_blur.py`'s measured 1/e autocorrelation
    radius of vanilla's own `colormap.dds`, in vanilla pixels — used
    unconverted because our canvas is built to match vanilla's own km/px
    (`docs/map_scale.md`), so a vanilla pixel and a canvas pixel already cover
    the same ground distance (`assumed`: this equates an autocorrelation
    e-folding radius with a Gaussian blur sigma, exact only for blurred white
    noise, not vanilla's actual texture — see the script's own docstring).
    """
    table = dict(_CK2_TO_CK3_TERRAIN if mapping is None else mapping)
    ck3_of_code = [table.get(name, default) if name else default for name in code_names]

    missing: set[str] = set()

    def _tint_for(ck3_key: str) -> tuple[int, int, int]:
        t = tint_map.get(ck3_key)
        if t is None:
            missing.add(ck3_key)
            t = tint_map.get(default, DEFAULT_TINT)
        return t

    n = len(code_names)
    r_lut = np.zeros(n, dtype=np.uint8)
    g_lut = np.zeros(n, dtype=np.uint8)
    b_lut = np.zeros(n, dtype=np.uint8)
    for code, ck3_key in enumerate(ck3_of_code):
        r, g, b = _tint_for(ck3_key)
        r_lut[code], g_lut[code], b_lut[code] = r, g, b

    for name in sorted(missing):
        warn(
            f"colormap: CK3 terrain '{name}' has no row in "
            "mappings/colormap_tints.csv; using the default terrain's tint"
        )

    rgb = np.stack([r_lut[codes], g_lut[codes], b_lut[codes]], axis=-1).astype(np.float32)

    water_rgb = tint_map.get("water", DEFAULT_TINT)
    rgb[water_mask] = water_rgb

    if blur_sigma > 0:
        for c in range(3):
            rgb[..., c] = gaussian_filter(rgb[..., c], blur_sigma)

    return np.clip(rgb, 0, 255).astype(np.uint8)


def downsample(rgb: np.ndarray, scale: float) -> np.ndarray:
    """Lanczos-resample ``rgb`` (h, w, 3) by ``scale`` (< 1 shrinks)."""
    if scale == 1.0:
        return rgb
    h, w = rgb.shape[:2]
    nw = max(1, round(w * scale))
    nh = max(1, round(h * scale))
    return np.asarray(Image.fromarray(rgb).resize((nw, nh), Image.LANCZOS))


def _mip_chain(rgba: np.ndarray) -> list[np.ndarray]:
    """Full mip chain down to 1x1, matching Godherja's shipped colormap.dds."""
    chain = [rgba]
    h, w = rgba.shape[:2]
    im = Image.fromarray(rgba)
    while h > 1 or w > 1:
        h, w = max(1, h // 2), max(1, w // 2)
        im = im.resize((w, h), Image.LANCZOS)
        chain.append(np.asarray(im))
    return chain


def header(width: int, height: int, *, mips: int = 1) -> bytes:
    """The 128-byte DDS header for uncompressed A8R8G8B8, BGRA byte order.

    Byte-for-byte the same fields as Elder Kings 2's (``mips=1``) or
    Godherja's (``mips>1``) shipped ``colormap.dds`` (`verified`, see module
    docstring); vanilla's own DXT5 header is not used.
    """
    h = bytearray(128)
    h[0:4] = b"DDS "
    flags = _DDSD | (_DDSD_MIPMAPCOUNT if mips > 1 else 0)
    pitch = width * 4
    struct.pack_into(
        "<7I", h, 4,
        124,  # dwSize
        flags,
        height,
        width,
        pitch,  # dwPitchOrLinearSize: row pitch, not a compressed linear size
        0,  # dwDepth
        mips if mips > 1 else 0,  # dwMipMapCount
    )
    struct.pack_into("<2I", h, 76, 32, _DDPF_RGB | _DDPF_ALPHAPIXELS)  # ddspf size, flags
    struct.pack_into("<2I", h, 84, 0, 32)  # fourCC (0 = uncompressed), RGBBitCount
    struct.pack_into("<4I", h, 92, _R_MASK, _G_MASK, _B_MASK, _A_MASK)
    caps = _DDSCAPS_TEXTURE
    if mips > 1:
        caps |= _DDSCAPS_COMPLEX | _DDSCAPS_MIPMAP
    struct.pack_into("<I", h, 108, caps)
    return bytes(h)


def save(rgb: np.ndarray, path: Path, *, mips: bool = True) -> None:
    """Write ``rgb`` as an uncompressed BGRA8 DDS.

    ``(h, w, 3)`` gets alpha = 255; ``(h, w, 4)`` keeps the alpha it carries,
    which is what ``ck2ck3.map.water`` needs — the water colour map's alpha is
    the gloss channel, not padding.

    ``mips=True`` (default) writes the full chain to 1x1, Godherja's shape;
    ``False`` writes only the base level, EK2's shape. Both load per the two
    reference mods (module docstring); the chain is kept by default for a
    smoother look at oblique camera angles.
    """
    h, w = rgb.shape[:2]
    if rgb.shape[-1] == 4:
        rgba = rgb.astype(np.uint8)
    else:
        alpha = np.full((h, w, 1), 255, dtype=np.uint8)
        rgba = np.concatenate([rgb.astype(np.uint8), alpha], axis=-1)
    levels = _mip_chain(rgba) if mips else [rgba]
    data = bytearray()
    for level in levels:
        bgra = level[..., [2, 1, 0, 3]]
        data += np.ascontiguousarray(bgra, dtype=np.uint8).tobytes()
    path.write_bytes(header(w, h, mips=len(levels)) + bytes(data))
