"""``gfx/map/map_object_data/map_table_*.txt`` — the 3D table under the map.

Zoomed out, CK3 shows the paper map lying on a physical table.  The table is
not a define and not a mesh we author: it is a handful of ``object={}`` entries
that place prebuilt entities (tabletop, tablecloth, candles, props, floor) with
one ``transform`` each, in the **same pixel frame as the locators** —
``"x y z  qx qy qz qw  sx sy sz"``.

Vanilla sizes them for a 9216x4608 sheet.  Neither Elder Kings 2 (8256x5504)
nor Godherja (8192x4096) rescales the mesh; both only move it, and EK2 gets
away with a map 19 % taller than vanilla's.  At 6784 — **47 %** taller — the
Faerûn sheet overhangs the table's north edge and the props intersect it
(`docs/evidence/map_ui_research.md` §3).

So this module rewrites vanilla's own files rather than inventing new ones:
every ``transform`` is re-centred on our canvas and scaled about the map centre
by the same factor, which keeps each entity's offset from the table centre
intact.  Everything else in the file — ``entity=``, ``layer=``,
``render_pass=``, the y offsets that set the stacking order — is passed through
byte-for-byte, so a style we know nothing about still works.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from pathlib import Path

#: vanilla canvas the shipped transforms were authored against
VANILLA_WIDTH = 9216
VANILLA_HEIGHT = 4608

#: the files vanilla ships, one per `map_table_style_*` in
#: `gfx/map/table_styles/table_styles.txt`
TABLE_FILES: tuple[str, ...] = (
    "map_table_western.txt",
    "map_table_ce1.txt",
    "map_table_ep3.txt",
    "map_table_tgp.txt",
)

MAP_OBJECT_DIR = "gfx/map/map_object_data"

_TRANSFORM = re.compile(r'transform="([^"]*)"', re.S)


def scale_factor(width: int, height: int) -> float:
    """How much bigger the table has to be than vanilla's.

    ``max`` of the two axis ratios, not the mean: the table has to *cover* the
    sheet on both axes, and being too wide is free — it renders
    ``MapUnderTerrain``, always below the map.
    """
    return max(width / VANILLA_WIDTH, height / VANILLA_HEIGHT)


def remap_transform(transform: str, *, width: int, height: int, k: float) -> str:
    """Re-centre and rescale one ``transform`` string.

    ``x``/``z`` move so the object keeps its offset from the map centre, scaled
    by ``k``; the three scale components are multiplied by ``k``; ``y`` and the
    rotation quaternion are untouched.
    """
    trailing = transform[len(transform.rstrip()) :]
    parts = transform.split()
    if len(parts) != 10:
        return transform
    v = [float(p) for p in parts]
    v[0] = width / 2.0 + (v[0] - VANILLA_WIDTH / 2.0) * k
    v[2] = height / 2.0 + (v[2] - VANILLA_HEIGHT / 2.0) * k
    v[7] *= k
    v[8] *= k
    v[9] *= k
    return " ".join(f"{x:.6f}" for x in v) + trailing


def render_table_file(text: str, *, width: int, height: int) -> str:
    """Rewrite one vanilla ``map_table_<style>.txt`` for our canvas."""
    k = scale_factor(width, height)
    banner = (
        "# GENERATED by ck2ck3 (lane map-ui) from the vanilla file of the same\n"
        f"# name. Canvas {width}x{height}; every transform re-centred on it and\n"
        f"# scaled by {k:.4f} = max({width}/{VANILLA_WIDTH}, {height}/{VANILLA_HEIGHT}),\n"
        "# so the table still covers a sheet that is not vanilla's aspect.\n"
        "# See docs/evidence/map_ui_research.md section 3.\n"
    )
    body = _TRANSFORM.sub(
        lambda m: 'transform="'
        + remap_transform(m.group(1), width=width, height=height, k=k)
        + '"',
        text.lstrip("﻿"),
    )
    return banner + body


def render_all(
    game_dir: Path | None, *, width: int, height: int, files: Iterable[str] = TABLE_FILES
) -> dict[str, str]:
    """``{mod-relative path: text}`` for every vanilla table file we can read.

    Returns ``{}`` when the CK3 install is not available: a missing table
    override leaves vanilla's behaviour, which is wrong but not fatal, and this
    step must not fail a run that has no game dir (the CLI's own tests).
    """
    if game_dir is None:
        return {}
    out: dict[str, str] = {}
    for name in files:
        src = Path(game_dir) / MAP_OBJECT_DIR / name
        if not src.exists():
            continue
        out[f"{MAP_OBJECT_DIR}/{name}"] = render_table_file(
            src.read_text(encoding="utf-8-sig", errors="replace"),
            width=width,
            height=height,
        )
    return out
