"""Writers for the CK3 ``map_data/`` text files and ``common/province_terrain/``.

Format facts (with file:line evidence) live in ``docs/formats_map.md``.  The
ones that shape this module:

* ``map_data/definition.csv`` row 0 is ``0;0;0;0;x;x;`` — 6 fields **and a
  trailing semicolon** (vanilla ``map_data/definition.csv:1``).
* ``map_data/default.map`` loads the heightmap through
  ``topology = "heightmap.heightmap"``, never ``heightmap.png``
  (vanilla ``map_data/default.map:7``).
* province-id lists in ``default.map`` use ``RANGE { first last }`` and
  ``LIST { a b c }``; ``max_provinces``, ``positions``, ``climate`` and
  ``terrain_definition`` are commented out in vanilla and in Elder Kings 2.
* ``map_data/adjacencies.csv`` header is
  ``From;To;Type;Through;start_x;start_y;stop_x;stop_y;Comment`` and the only
  ``Type`` values vanilla uses are ``sea`` and ``river_large``.
* ``common/province_terrain/*.txt`` and ``map_data/heightmap.heightmap`` are
  written by vanilla **with a UTF-8 BOM**; the other map_data text files are not.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Iterable, Sequence



from .ck2read import Ck2Adjacency, Ck2GeoRegion
from .config import Canvas
from .idmap import Ck3Province, IdMap

GENERATED = "# GENERATED by ck2ck3 (lane map-physical). Do not hand-edit."

#: Script files CK3 wants as UTF-8 **with** BOM. `verified` by ck3-tiger
#: ("warning(encoding): Expected UTF-8 BOM encoding") on everything we write
#: under common/ and history/, plus map_data/geographical_regions. The flat
#: map_data files (definition.csv, default.map, climate.txt, ...) must NOT have
#: one - vanilla's do not.
BOM_PREFIXES = (
    "common/",
    "history/",
    "map_data/geographical_regions/",
    "map_data/heightmap.heightmap",
)


def needs_bom(rel: str) -> bool:
    """Whether the output file at ``rel`` must start with a UTF-8 BOM."""
    return rel.startswith(BOM_PREFIXES)


def _joined(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# id list formatting
# --------------------------------------------------------------------------- #
def to_ranges(ids: Iterable[int]) -> list[tuple[int, int]]:
    """Collapse a set of ids into sorted inclusive runs."""
    out: list[tuple[int, int]] = []
    for i in sorted(set(ids)):
        if out and i == out[-1][1] + 1:
            out[-1] = (out[-1][0], i)
        else:
            out.append((i, i))
    return out


def format_id_lists(key: str, ids: Iterable[int], *, per_line: int = 20) -> list[str]:
    """``key = RANGE { a b }`` for runs of 3+, ``key = LIST { ... }`` otherwise.

    Runs of one or two ids are cheaper as a LIST, and vanilla mixes both freely
    (``map_data/default.map:19-22`` RANGE, ``:31`` ``sea_zones = LIST { 977 }``).
    """
    ranges = to_ranges(ids)
    lines: list[str] = []
    singles: list[int] = []
    for a, b in ranges:
        if b - a >= 2:
            lines.append(f"{key} = RANGE {{ {a} {b} }}")
        else:
            singles.extend(range(a, b + 1))
    for i in range(0, len(singles), per_line):
        chunk = " ".join(str(v) for v in singles[i : i + per_line])
        lines.append(f"{key} = LIST {{ {chunk} }}")
    return lines


# --------------------------------------------------------------------------- #
# definition.csv
# --------------------------------------------------------------------------- #
def render_definition_csv(
    provinces: Sequence[Ck3Province], names: dict[int, str] | None = None
) -> str:
    """CK3 ``map_data/definition.csv``: ``id;r;g;b;name;x;`` with a 0 row first.

    Written with ``\\n`` line endings and no BOM, matching vanilla.

    Column 5 is an **identifier**, not a display name: vanilla writes
    ``VESTFIRDIR`` and ck3-tiger reads the column as a localisation key.  Pass
    ``names`` (CK3 province id -> identifier) to supply them; without it the CK2
    name is used, with ``;`` replaced by ``,`` so the row cannot be corrupted.
    """
    lines = ["0;0;0;0;x;x;"]
    seen_ids: set[int] = set()
    seen_rgb: dict[tuple[int, int, int], int] = {}
    for p in provinces:
        if p.id in seen_ids:
            raise ValueError(f"duplicate CK3 province id {p.id}")
        if p.rgb in seen_rgb:
            raise ValueError(
                f"CK3 provinces {seen_rgb[p.rgb]} and {p.id} share colour {p.rgb}"
            )
        seen_ids.add(p.id)
        seen_rgb[p.rgb] = p.id
        name = (names or {}).get(p.id) or p.name or f"province_{p.id}"
        name = name.replace(";", ",")
        lines.append(f"{p.id};{p.rgb[0]};{p.rgb[1]};{p.rgb[2]};{name};x;")
    return _joined(lines)


# --------------------------------------------------------------------------- #
# default.map
# --------------------------------------------------------------------------- #
def render_default_map(
    idmap: IdMap,
    *,
    sea_zone_names: dict[int, str] | None = None,
    continent_file: str | None = "continent.txt",
    island_region_file: str | None = "island_region.txt",
) -> str:
    """CK3 ``map_data/default.map``.

    ``max_provinces``, ``positions``, ``climate`` and ``terrain_definition`` are
    left commented out exactly as vanilla and Elder Kings 2 do; the game derives
    province count from ``definition.csv`` and generates positions itself.
    """
    seas = [p.id for p in idmap.provinces if p.is_sea]
    lakes = [p.id for p in idmap.provinces if p.is_lake]
    rivers = [p.id for p in idmap.provinces if p.is_river]
    impassable = [p.id for p in idmap.provinces if p.is_impassable]

    out: list[str] = [
        GENERATED,
        f"#max_provinces = {len(idmap.provinces) + 1}",
        'definitions = "definition.csv"',
        'provinces = "provinces.png"',
        '#positions = "positions.txt"',
        'rivers = "rivers.png"',
        '#terrain_definition = "terrain.txt"',
        'topology = "heightmap.heightmap"',
        '#tree_definition = "trees.bmp"',
    ]
    if continent_file:
        out.append(f'continent = "{continent_file}"')
    out.append('adjacencies = "adjacencies.csv"')
    out.append('#climate = "climate.txt"')
    if island_region_file:
        out.append(f'island_region = "{island_region_file}"')
    out.append('seasons = "seasons.txt"')

    out += ["", "#############", "# SEA ZONES", "#############"]
    out += _named_id_lists("sea_zones", seas, sea_zone_names)

    out += ["", "###############", "# MAJOR RIVERS", "###############"]
    out += format_id_lists("river_provinces", rivers) or ["# none"]

    out += ["", "########", "# LAKES", "########"]
    out += format_id_lists("lakes", lakes) or ["# none"]

    out += ["", "#####################", "# IMPASSABLE TERRAIN", "#####################"]
    out += format_id_lists("impassable_mountains", impassable) or ["# none"]

    return _joined(out)


def _named_id_lists(
    key: str, ids: list[int], names: dict[int, str] | None
) -> list[str]:
    """Group ids by their source sea-zone name so the comments survive."""
    if not names:
        return format_id_lists(key, ids) or ["# none"]
    groups: dict[str, list[int]] = {}
    for i in ids:
        groups.setdefault(names.get(i, ""), []).append(i)
    lines: list[str] = []
    for name in sorted(groups, key=lambda n: min(groups[n])):
        if name:
            lines.append(f"# {name}")
        lines += format_id_lists(key, groups[name])
    return lines or ["# none"]


# --------------------------------------------------------------------------- #
# adjacencies.csv
# --------------------------------------------------------------------------- #
#: CK2 adjacency type -> CK3 type. CK3 1.19 only accepts these two
#: (vanilla map_data/adjacencies.csv column 3 has exactly `sea` and `river_large`).
CK2_TO_CK3_ADJACENCY = {
    "sea": "sea",
    "river": "river_large",
    "major_river": "river_large",
    "canal": "sea",
    "": "sea",
}


def render_adjacencies_csv(
    adjacencies: Sequence[Ck2Adjacency],
    idmap: IdMap,
    *,
    dropped_log: list[str] | None = None,
) -> tuple[str, int]:
    """CK3 ``map_data/adjacencies.csv``.

    ``start_x``/``start_y``/``stop_x``/``stop_y`` are the pixel coordinates of
    the crossing's endpoints; CK2 does not store them, so ``-1`` is written and
    the game picks the province centres (vanilla uses real values but ``-1`` is
    accepted, `assumed`).  Rows whose From/To/Through did not survive the id
    remap are dropped and logged.
    """
    rows = [["From", "To", "Type", "Through", "start_x", "start_y", "stop_x", "stop_y", "Comment"]]
    kept = 0
    for a in adjacencies:
        f, t = idmap.ck3(a.from_id), idmap.ck3(a.to_id)
        through = idmap.ck3(a.through) if a.through > 0 else -1
        if f is None or t is None:
            if dropped_log is not None:
                dropped_log.append(
                    f"adjacency {a.from_id}->{a.to_id}: endpoint lost in remap"
                )
            continue
        if a.through > 0 and through is None:
            if dropped_log is not None:
                dropped_log.append(
                    f"adjacency {a.from_id}->{a.to_id}: Through province "
                    f"{a.through} did not survive the id remap; row dropped"
                )
            continue
        ck3_type = CK2_TO_CK3_ADJACENCY.get(a.type.lower(), "sea")
        if through is None or through < 0:
            # CK3 requires a real province id in the Through column on EVERY
            # row, whatever the type (`verified`: ck3-tiger "expected province
            # id" pointing at a `-1` Through on a `sea` row). CK2 allows -1, so
            # such a row simply cannot be converted - there is nothing to cross
            # through - and inventing a province would break the no-invention
            # rule. Dropped and logged.
            if dropped_log is not None:
                dropped_log.append(
                    f"adjacency {a.from_id}->{a.to_id} ({a.type}): CK2 gives no "
                    "Through province and CK3 requires one; row dropped"
                )
            continue
        rows.append(
            [f, t, ck3_type, through, -1, -1, -1, -1, a.comment.replace(";", ",")]
        )
        kept += 1
    # CK3 requires a terminator row of -1s at the end of adjacencies.csv
    # (`verified`: ck3-tiger "CK3 needs a line with all `-1;` at the end of this
    # file"; vanilla map_data/adjacencies.csv's last line is
    # `-1;-1;;-1;-1;-1;-1;-1;`, with an empty Type field).
    rows.append([-1, -1, "", -1, -1, -1, -1, -1, ""])
    buf = io.StringIO()
    csv.writer(buf, delimiter=";", lineterminator="\n").writerows(rows)
    return buf.getvalue(), kept


# --------------------------------------------------------------------------- #
# climate.txt
# --------------------------------------------------------------------------- #
def render_climate(ck2_climate: dict[str, list[int]], idmap: IdMap) -> str:
    """CK3 ``map_data/climate.txt``.

    CK2 and CK3 use the same three keys, so this is a pure id remap.  Note the
    file is commented out in vanilla ``default.map`` and in our own; it is
    emitted anyway so a later lane can switch it on with a one-line change.
    """
    out = [GENERATED]
    # CK2 lists some provinces in two climate blocks (Faerun has 2, e.g. 2417
    # in both severe_winter and mild_winter). CK3 rejects that
    # ("warning(conflict): province N has two climates"), so the first block a
    # province appears in wins and the duplicate is dropped.
    claimed: set[int] = set()
    for key in ("mild_winter", "normal_winter", "severe_winter"):
        ids = [i for i in idmap.remap_ids(ck2_climate.get(key, [])) if i not in claimed]
        claimed.update(ids)
        out.append(f"{key} = {{")
        for i in range(0, len(ids), 20):
            out.append("\t" + " ".join(str(v) for v in ids[i : i + 20]))
        out.append("}")
    return _joined(out)


# --------------------------------------------------------------------------- #
# island_region.txt
# --------------------------------------------------------------------------- #
def render_island_region(ck2_islands: dict[str, list[int]], idmap: IdMap) -> str:
    """CK3 ``map_data/island_region.txt`` — ``provinces = { ... }`` per region.

    CK3 also accepts ``duchies``/``counties`` here
    (vanilla ``map_data/island_region.txt:7-9``), but provinces need no title
    layer, so the converter uses them and stays independent of the titles lane.
    """
    out = [
        GENERATED,
        "# Island regions - no land path from the continent (CK3 needs these for pathfinding).",
        "# Converted from CK2 map/island_region.txt; province ids remapped.",
        "",
    ]
    for name, ck2_ids in ck2_islands.items():
        ids = idmap.remap_ids(ck2_ids)
        if not ids:
            out.append(f"# {name}: every province lost in the id remap")
            continue
        out.append(f"{name} = {{")
        out.append("\tprovinces = { " + " ".join(str(i) for i in ids) + " }")
        out.append("}")
    return _joined(out)


# --------------------------------------------------------------------------- #
# geographical_regions/
# --------------------------------------------------------------------------- #
def render_geographical_regions(
    regions: Sequence[Ck2GeoRegion], idmap: IdMap
) -> str:
    """CK3 ``map_data/geographical_regions/<prefix>_regions.txt``.

    CK2 geographical regions list **duchies**, and duchy keys keep their CK2
    names (the titles lane emits the same ``d_*`` keys), so duchy lists pass
    through unchanged.  Sub-region references also pass through, but CK3 needs a
    region declared before it is referenced (vanilla
    ``map_data/geographical_regions/geographical_region.txt:8``), so parents are
    emitted after their children by a topological sort.
    """
    out = [
        GENERATED,
        "# Converted from CK2 map/geographical_region.txt.",
        "# Duchy keys pass through unchanged; province ids are remapped.",
        "# CK3 requires a sub-region to be declared before its parent.",
        "",
    ]
    for reg in _topo_sort_regions(regions):
        out.append(f"{reg.name} = {{")
        if reg.duchies:
            out.append("\tduchies = { " + " ".join(reg.duchies) + " }")
        if reg.regions:
            out.append("\tregions = { " + " ".join(reg.regions) + " }")
        ids = idmap.remap_ids(reg.provinces)
        if ids:
            out.append("\tprovinces = { " + " ".join(str(i) for i in ids) + " }")
        if not (reg.duchies or reg.regions or ids):
            out.append("\t# empty in CK2, or everything was lost in the id remap")
        out.append("}")
    return _joined(out)


def _topo_sort_regions(regions: Sequence[Ck2GeoRegion]) -> list[Ck2GeoRegion]:
    """Children before parents; cycles and unknown refs keep file order."""
    by_name = {r.name: r for r in regions}
    out: list[Ck2GeoRegion] = []
    state: dict[str, int] = {}  # 0 = visiting, 1 = done

    def visit(name: str) -> None:
        if state.get(name) == 1 or name not in by_name:
            return
        if state.get(name) == 0:  # cycle: bail, keep whatever order we have
            return
        state[name] = 0
        for child in by_name[name].regions:
            visit(child)
        state[name] = 1
        out.append(by_name[name])

    for r in regions:
        visit(r.name)
    return out


# --------------------------------------------------------------------------- #
# common/province_terrain/
# --------------------------------------------------------------------------- #
def render_province_terrain(
    terrain_by_id: dict[int, str], *, default: str = "plains"
) -> str:
    """CK3 ``common/province_terrain/<prefix>_province_terrain.txt``.

    Format is ``<province_id>=<terrain_key>`` after three default lines
    (vanilla ``common/province_terrain/00_province_terrain.txt:1-3``).  Written
    with a UTF-8 BOM because vanilla is.  Sea provinces are omitted: the
    ``default_sea`` line covers them and ``default.map`` already declares which
    ids are water.
    """
    out = [
        GENERATED,
        f"default_land={default}",
        "default_sea=sea",
        "default_coastal_sea=coastal_sea",
    ]
    out += [f"{pid}={key}" for pid, key in sorted(terrain_by_id.items())]
    return _joined(out)


# --------------------------------------------------------------------------- #
# small files
# --------------------------------------------------------------------------- #
def render_continent(*, name: str, province_ids: Iterable[int]) -> str:
    """CK3 ``map_data/continent.txt``.

    CK2 Faerûn ships an empty ``continent.txt`` (``map/continent.txt:1``
    ``#empty for now``), so the converter emits a single continent holding every
    land province rather than inventing a continent breakdown.
    """
    ids = sorted(set(province_ids))
    out = [GENERATED, f"{name} = {{", "\tid = 1", "\tprovinces = {"]
    for i in range(0, len(ids), 20):
        out.append("\t\t" + " ".join(str(v) for v in ids[i : i + 20]))
    out += ["\t}", "}"]
    return _joined(out)


def render_seasons() -> str:
    """CK3 ``map_data/seasons.txt`` — referenced by default.map; a stub is enough."""
    return GENERATED + "\n"


def render_positions_stub(canvas: Canvas) -> str:
    """Empty ``map_data/positions.txt``, the Godherja pattern.

    ``positions`` stays commented out in ``default.map`` so the game generates
    positions itself; the file exists only so switching the line on does not
    break.  CK2 positions are per province and there are no barony coordinates
    to import, so nothing is lost here (see CLAUDE.md invariants).
    """
    return (
        f"{GENERATED}\n# Intentionally empty: CK3 generates positions.\n"
        f"# Canvas {canvas.width}x{canvas.height}, scale factor {canvas.factor:.6f}.\n"
    )
