"""Regional tree mix: P(mesh | terrain, climate, latitude band).

`docs/step_map_paint.md` §9.9. The sampler must be deterministic across
processes, coherent at the stand scale, faithful to the measured conditional
table, and must not change the density contract §9.2 fixed (how many trees
and where) — only which mesh each one gets.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from ck2ck3.map import tree_scatter

REPO = Path(__file__).resolve().parents[1]

PINE = "tree_pine_01_b_generator_1.txt"
LEAF = "tree_leaf_high_generator_1.txt"
PALM = "tree_palm_generator_1.txt"


def _mix_csv(tmp_path: Path, body: str, name: str = "tree_mix.csv") -> Path:
    p = tmp_path / name
    p.write_text(
        "# GENERATED by a test, and a comment line every reader must skip\n"
        "ck3_terrain,climate,lat_band,file,count,p\n" + body,
        encoding="utf-8",
    )
    return p


# --------------------------------------------------------------- the table


def test_read_mix_table_skips_comments_and_normalises(tmp_path):
    path = _mix_csv(
        tmp_path,
        f"forest,severe,0,{PINE},30,0.75\n"
        f"forest,severe,0,{LEAF},10,0.25\n"
        # a hand-trimmed condition whose shares no longer sum to 1
        f"forest,none,*,{LEAF},10,0.4\n",
    )
    table = tree_scatter.read_mix_table(path)
    assert table[("forest", "severe", "0")].files == (LEAF, PINE)
    assert table[("forest", "severe", "0")].cdf == (0.25, 1.0)
    assert table[("forest", "none", "*")].cdf == (1.0,)


def test_read_mix_table_missing_file_is_empty_not_an_error(tmp_path):
    assert tree_scatter.read_mix_table(tmp_path / "nope.csv") == {}


def test_resolve_mix_tries_latitude_before_climate():
    """Measured, not assumed: over vanilla's own 549,126 instances the
    latitude band explains far more of the species choice than the climate
    zone (docs/evidence/vanilla_tree_mix_conditioning.csv, 1.626 vs 2.008
    bits of cross-entropy against terrain alone at 2.056)."""
    d_full = tree_scatter.MixDist((PINE,), (1.0,))
    d_clim = tree_scatter.MixDist((LEAF,), (1.0,))
    d_band = tree_scatter.MixDist((PALM,), (1.0,))
    d_terr = tree_scatter.MixDist(("reeds_01_generator_1.txt",), (1.0,))
    table = {
        ("forest", "severe", "0"): d_full,
        ("forest", "severe", "*"): d_clim,
        ("forest", "*", "0"): d_band,
        ("forest", "*", "*"): d_terr,
    }
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (
        d_full, "terrain+climate+band")
    del table[("forest", "severe", "0")]
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (
        d_band, "terrain+band")
    del table[("forest", "*", "0")]
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (
        d_clim, "terrain+climate")
    # ...but a neighbouring band beats the climate marginal: bands are
    # ordinal and vanilla has no forest at all in its own band 0
    table[("forest", "*", "1")] = d_band
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (
        d_band, "terrain+neighbour_band")
    del table[("forest", "*", "1")]
    del table[("forest", "severe", "*")]
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (
        d_terr, "terrain")
    del table[("forest", "*", "*")]
    assert tree_scatter.resolve_mix(table, "forest", "severe", 0) == (None, "none")


def test_apply_mix_overrides_replaces_a_condition_and_leaves_the_rest(tmp_path):
    table = tree_scatter.read_mix_table(
        _mix_csv(tmp_path, f"drylands,none,9,{LEAF},99,1.0\n"
                           f"forest,none,0,{PINE},99,1.0\n")
    )
    overrides = tree_scatter.read_mix_table(
        _mix_csv(tmp_path, f"drylands,none,9,{PALM},,1\n", name="ov.csv")
    )
    merged = tree_scatter.apply_mix_overrides(table, overrides)
    assert merged[("drylands", "none", "9")].files == (PALM,)
    assert merged[("forest", "none", "0")].files == (PINE,)


# ------------------------------------------------------------- the sampler


def _points(n: int, x0: float = 0.0, y0: float = 0.0, spread: float = 1.0):
    xs = x0 + (np.arange(n) % 8) * spread
    ys = y0 + (np.arange(n) // 8) * spread
    return xs.astype(float), ys.astype(float)


def test_sampler_is_deterministic():
    xs, ys = _points(400, spread=7.0)
    args = dict(
        table={("forest", "none", "0"): tree_scatter.MixDist(
            (LEAF, PINE), (0.5, 1.0))},
        mesh_of_terrain={"forest": LEAF},
        cell_px=24,
        seed=99,
        coherence=0.5,
    )
    t = np.array(["forest"] * 400, dtype=object)
    c = np.array(["none"] * 400, dtype=object)
    b = np.zeros(400, dtype=int)
    a1, f1, _ = tree_scatter.assign_regional_meshes(xs, ys, t, c, b, **args)
    a2, f2, _ = tree_scatter.assign_regional_meshes(xs, ys, t, c, b, **args)
    assert f1 == f2
    assert np.array_equal(a1, a2)


def test_cell_uniform_is_stable_across_processes():
    """crc32, never hash(): the yaw seed already cost 1.4 M diff lines."""
    import subprocess
    import sys

    v = tree_scatter.cell_uniform(np.array([3, 3, 4]), np.array([7, 7, 7]), 4242)
    assert v[0] == v[1] and v[0] != v[2]
    assert 0.0 <= v[0] < 1.0
    code = (
        "import numpy as np;"
        "from ck2ck3.map.tree_scatter import cell_uniform;"
        "print(cell_uniform(np.array([3]), np.array([7]), 4242)[0])"
    )
    outs = {
        subprocess.run(
            [sys.executable, "-c", code],
            env={"PYTHONHASHSEED": str(i), "PYTHONPATH": "src"},
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        for i in (1, 2)
    }
    assert len(outs) == 1
    assert float(outs.pop()) == pytest.approx(v[0])


def test_full_coherence_makes_one_cell_one_species():
    """Vanilla's species form stands; per-pixel salt and pepper is the bug."""
    # 64 points inside a single 24 px cell, all the same condition
    xs = np.linspace(0.5, 23.5, 64)
    ys = np.full(64, 5.0)
    t = np.array(["forest"] * 64, dtype=object)
    c = np.array(["none"] * 64, dtype=object)
    b = np.zeros(64, dtype=int)
    ids, files, _ = tree_scatter.assign_regional_meshes(
        xs, ys, t, c, b,
        {("forest", "none", "0"): tree_scatter.MixDist((LEAF, PINE), (0.5, 1.0))},
        {"forest": LEAF},
        cell_px=24, seed=1, coherence=1.0,
    )
    assert len(set(ids.tolist())) == 1
    # ...and a different cell can differ: 256 cells cannot all agree
    xs2 = np.arange(256) * 24.0 + 1.0
    ys2 = np.full(256, 5.0)
    ids2, _f, _l = tree_scatter.assign_regional_meshes(
        xs2, ys2, np.array(["forest"] * 256, dtype=object),
        np.array(["none"] * 256, dtype=object), np.zeros(256, dtype=int),
        {("forest", "none", "0"): tree_scatter.MixDist((LEAF, PINE), (0.5, 1.0))},
        {"forest": LEAF},
        cell_px=24, seed=1, coherence=1.0,
    )
    assert len(set(ids2.tolist())) == 2


def test_zero_coherence_mixes_inside_one_cell():
    xs = np.linspace(0.5, 23.5, 200)
    ys = np.full(200, 5.0)
    ids, _f, _l = tree_scatter.assign_regional_meshes(
        xs, ys,
        np.array(["forest"] * 200, dtype=object),
        np.array(["none"] * 200, dtype=object),
        np.zeros(200, dtype=int),
        {("forest", "none", "0"): tree_scatter.MixDist((LEAF, PINE), (0.5, 1.0))},
        {"forest": LEAF},
        cell_px=24, seed=1, coherence=0.0,
    )
    assert len(set(ids.tolist())) == 2


def test_sampler_respects_the_conditional_table():
    """Pines north, palms south — as a measurement, not a claim."""
    n = 2000
    xs = (np.arange(n) % 50) * 31.0
    ys = np.where(np.arange(n) < n // 2, 10.0, 990.0)  # bands 0 and 9
    t = np.array(["forest"] * n, dtype=object)
    c = np.array(["none"] * n, dtype=object)
    b = tree_scatter.lat_band(ys, 1000, 10)
    table = {
        ("forest", "none", "0"): tree_scatter.MixDist((PINE,), (1.0,)),
        ("forest", "none", "9"): tree_scatter.MixDist((PALM,), (1.0,)),
    }
    ids, files, levels = tree_scatter.assign_regional_meshes(
        xs, ys, t, c, b, table, {"forest": LEAF}, cell_px=24, seed=5
    )
    north = {files[i] for i in ids[: n // 2].tolist()}
    south = {files[i] for i in ids[n // 2:].tolist()}
    assert north == {PINE}
    assert south == {PALM}
    assert levels["terrain+climate+band"] == n


def test_sampler_hits_the_measured_shares():
    n = 20000
    xs = (np.arange(n) % 200) * 29.0
    ys = ((np.arange(n) // 200) % 100) * 29.0
    ids, files, _ = tree_scatter.assign_regional_meshes(
        xs, ys,
        np.array(["forest"] * n, dtype=object),
        np.array(["none"] * n, dtype=object),
        np.zeros(n, dtype=int),
        {("forest", "none", "0"): tree_scatter.MixDist((LEAF, PINE), (0.7, 1.0))},
        {"forest": LEAF},
        cell_px=8, seed=11, coherence=0.5,
    )
    share_leaf = float((np.array(files)[ids] == LEAF).mean())
    assert share_leaf == pytest.approx(0.7, abs=0.03)


def test_terrain_with_no_mesh_row_is_still_dropped():
    """mappings/tree_meshes.csv stays the eligibility gate: the density
    contract (placed/dropped) must not move when the mix table is added."""
    n = 10
    xs, ys = _points(n)
    ids, _files, levels = tree_scatter.assign_regional_meshes(
        xs, ys,
        np.array(["desert"] * n, dtype=object),
        np.array(["none"] * n, dtype=object),
        np.zeros(n, dtype=int),
        # the table *does* have desert rows (vanilla plants palms there)
        {("desert", "none", "0"): tree_scatter.MixDist((PALM,), (1.0,))},
        {"desert": ""},  # ...but our own art table says bare sand
        cell_px=24, seed=1,
    )
    assert (ids == -1).all()
    assert levels == {"gated_no_mesh_row": n}


def test_falls_back_to_tree_meshes_csv_when_the_table_is_silent():
    n = 5
    xs, ys = _points(n)
    ids, files, levels = tree_scatter.assign_regional_meshes(
        xs, ys,
        np.array(["oasis"] * n, dtype=object),
        np.array(["none"] * n, dtype=object),
        np.zeros(n, dtype=int),
        {}, {"oasis": PALM}, cell_px=24, seed=1,
    )
    assert {files[i] for i in ids.tolist()} == {PALM}
    assert levels == {"tree_meshes.csv": n}


def test_lat_band_is_a_fractional_canvas_row():
    y = np.array([0.0, 339.0, 3392.0, 6783.0, 99999.0])
    assert tree_scatter.lat_band(y, 6784, 10).tolist() == [0, 0, 5, 9, 9]


# ------------------------------------------------------- the whole scatter


def _grid(shape, keys, key):
    return np.full(shape, keys.index(key), dtype=np.uint8)


def test_regional_scatter_places_the_same_points_as_the_terrain_only_one():
    """Density contract: only the *which mesh* step changes (§9.2)."""
    eligible = np.zeros((60, 60), dtype=bool)
    eligible[10:50, 10:50] = True
    tkeys = ["forest"]
    ckeys = ["severe"]
    tcode = _grid(eligible.shape, tkeys, "forest")
    ccode = _grid(eligible.shape, ckeys, "severe")
    mesh = {"forest": LEAF}
    plain, d0, _dbt = tree_scatter.scatter(
        eligible, tcode, tkeys, mesh, target_total=500, seed=3
    )
    reg, d1, _dbt2, _lv = tree_scatter.scatter_regional(
        eligible, tcode, tkeys, ccode, ckeys, mesh,
        {("forest", "severe", "*"): tree_scatter.MixDist((PINE,), (1.0,))},
        canvas_height=60, target_total=500, seed=3,
    )
    assert d0 == d1 == 0
    assert sum(v.shape[0] for v in plain.values()) == 500
    assert sum(v.shape[0] for v in reg.values()) == 500
    assert set(plain) == {LEAF} and set(reg) == {PINE}
    assert np.array_equal(
        np.sort(plain[LEAF], axis=0), np.sort(reg[PINE], axis=0)
    )


def _fake_game_dir(tmp_path: Path, files: list[str]) -> Path:
    d = tmp_path / "game" / tree_scatter.GENERATED_DIR
    d.mkdir(parents=True)
    for i, f in enumerate(files):
        (d / f).write_text(
            "object={\n"
            f'\tname="{f[:-4]}_0"\n'
            "\trender_pass=Map\n"
            "\tclamp_to_water_level=no\n"
            "\tgenerated_content=yes\n"
            '\tlayer="tree_high_layer"\n'
            f'\tpdxmesh="mesh_{i}"\n'
            "\tcount=1\n"
            '\ttransform="1 0 1 0 0 0 1 1 1 1"\n'
            "}\n",
            encoding="utf-8",
        )
    return tmp_path / "game"


def test_render_all_stubs_every_generator_the_mix_never_uses(tmp_path):
    """All 18 vanilla files stay overridden; an unused one is an honest
    empty stub, never a fabricated block (§9.2)."""
    all_files = [PINE, LEAF, PALM, "tree_sakura_01_generator.txt"]
    game = _fake_game_dir(tmp_path, all_files)
    mesh_csv = tmp_path / "tree_meshes.csv"
    mesh_csv.write_text(
        f"ck3_terrain,file,note\nforest,{LEAF},x\n", encoding="utf-8"
    )
    eligible = np.ones((20, 20), dtype=bool)
    tkeys, ckeys = ["forest"], ["severe"]
    out, counts, dropped, _by_t, levels = tree_scatter.render_all(
        game,
        mesh_csv,
        eligible,
        _grid(eligible.shape, tkeys, "forest"),
        tkeys,
        20,
        target_total=100,
        seed=7,
        mix_table={("forest", "severe", "*"): tree_scatter.MixDist(
            (PINE,), (1.0,))},
        climate_code=_grid(eligible.shape, ckeys, "severe"),
        climate_keys=ckeys,
    )
    assert set(out) == {
        f"{tree_scatter.GENERATED_DIR}/{f}" for f in all_files
    }
    assert counts == {PINE: 100}
    assert dropped == 0
    assert levels == {"terrain+climate": 100}
    for f in (LEAF, PALM, "tree_sakura_01_generator.txt"):
        assert "instances={\n\t}\n" in out[f"{tree_scatter.GENERATED_DIR}/{f}"]
    assert "count=100\n" in out[f"{tree_scatter.GENERATED_DIR}/{PINE}"]


def test_render_all_without_a_mix_table_is_the_terrain_only_path(tmp_path):
    game = _fake_game_dir(tmp_path, [PINE, LEAF])
    mesh_csv = tmp_path / "tree_meshes.csv"
    mesh_csv.write_text(
        f"ck3_terrain,file,note\nforest,{LEAF},x\n", encoding="utf-8"
    )
    eligible = np.ones((20, 20), dtype=bool)
    tkeys = ["forest"]
    _out, counts, _d, _bt, levels = tree_scatter.render_all(
        game, mesh_csv, eligible, _grid(eligible.shape, tkeys, "forest"),
        tkeys, 20, target_total=50, seed=7,
    )
    assert counts == {LEAF: 50}
    assert levels == {}


# ------------------------------------------------- the shipped table + CLI


def test_shipped_mix_csv_is_well_formed_and_names_real_generators():
    table = tree_scatter.read_mix_table(REPO / "mappings" / "tree_mix.csv")
    assert len(table) > 100, "mappings/tree_mix.csv looks empty"
    mesh = tree_scatter.read_mesh_table(REPO / "mappings" / "tree_meshes.csv")
    for key, dist in table.items():
        assert dist.cdf[-1] == pytest.approx(1.0)
        assert list(dist.cdf) == sorted(dist.cdf)
        assert key[1] == tree_scatter.MIX_WILDCARD or key[1] in {
            "none", "mild", "normal", "severe"
        }
    # every terrain our own art table plants trees on resolves to something
    for terrain, f in mesh.items():
        if not f:
            continue
        dist, _level = tree_scatter.resolve_mix(table, terrain, "none", 5)
        assert dist is not None, f"no mix row reachable for terrain {terrain}"


def test_mix_csv_bands_match_the_sampler():
    """The table's band count and `tree_scatter.N_LAT_BANDS` must agree —
    they are written by two different programs."""
    import csv

    path = REPO / "mappings" / "tree_mix.csv"
    with path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(
            csv.DictReader(line for line in fh if not line.lstrip().startswith("#"))
        )
    bands = {
        int(r["lat_band"])
        for r in rows
        if r["lat_band"] != tree_scatter.MIX_WILDCARD
    }
    assert bands == set(range(tree_scatter.N_LAT_BANDS))


def test_cli_config_builder_reads_the_tree_keys():
    """A `[map] trees*` key the REAL CLI builder never reads is a silent
    no-op — the `[map] colormap = false` bug, twice over."""
    from ck2ck3.steps import map as map_step

    class Cfg:
        raw = {"map": {"vanilla_km_per_px": 1.0, "source_km_per_px": 1.0,
                       "trees": False,
                       "trees_regional": False,
                       "trees_seed": 7,
                       "trees_cell_px": 99,
                       "trees_cell_coherence": 0.25,
                       "trees_mix_csv": "mappings/other.csv"}}
        path = Path("configs/x.toml")
        out = Path("/tmp/out")
        prefix = "fae"
        bookmark_date = (1357, 1, 1)
        name = "n"
        version = "0"
        supported_version = "1.19.*"

    class Ctx:
        config = Cfg()

        def ck2(self, *parts):
            return Path("/tmp/ck2").joinpath(*parts)

        def ck3(self, *parts):
            return Path("/tmp/ck3").joinpath(*parts)

    cfg = map_step._map_config(Ctx())
    assert cfg.trees is False
    assert cfg.trees_regional is False
    assert cfg.trees_seed == 7
    assert cfg.trees_cell_px == 99
    assert cfg.trees_cell_coherence == 0.25
    assert cfg.trees_mix_csv == Path("mappings/other.csv")
    for k in ("trees", "trees_regional", "trees_seed", "trees_cell_px",
              "trees_cell_coherence", "trees_mix_csv"):
        Cfg.raw["map"].pop(k)
    cfg = map_step._map_config(Ctx())
    assert cfg.trees is True
    assert cfg.trees_regional is True
    assert cfg.trees_seed == 4242
    assert cfg.trees_cell_px == 24
    assert cfg.trees_mix_csv == Path("mappings/tree_mix.csv")
    assert cfg.trees_mix_overrides_csv == Path("overrides/tree_mix.csv")
    assert cfg.trees_csv == Path("mappings/tree_meshes.csv")


def test_overrides_tree_mix_csv_is_readable_and_ships_empty():
    """The human hook exists, is comment-skipping, and forces nothing yet."""
    assert (REPO / "overrides" / "tree_mix.csv").is_file()
    assert tree_scatter.read_mix_table(REPO / "overrides" / "tree_mix.csv") == {}
