#!/usr/bin/env python3
"""`docs/evidence/vanilla_paint_vs_relief.csv` -> `mappings/relief_paint.csv`.

Mirrors the `measure_vanilla_tree_mix.py` -> `build_tree_mix_csv.py` split
(`docs/step_map_paint.md` §9.9): the measurement script is free to change its
binning or add axes without a conversion run depending on it; this script
turns the measurement into the small table `ck2ck3.map.relief_paint` actually
reads, and a normal `map` step run has no dependency on
`docs/evidence/*.csv`.

Each measured row's `category_shares` field ("cat=share;cat=share;...") is
already sorted descending by `measure_vanilla_relief_paint.py`; this script
passes it through unchanged (it is the PROPORTIONS `relief_paint.py`'s
stochastic family sampling needs — collapsing to rank order alone, the
original v2 design, reproduced vanilla's *top-1* family almost everywhere
and nothing else: coordinator review measured `mountains` painting 93% rock
against vanilla's own 36%, because an argmax-of-smoothed-rank can never
paint the minority families a real vanilla bin actually mixes in). Also
parses the category names into a `;`-joined rank column for anything that
still wants order only, and drops rows below `--min-count` (default 30, the
same floor the measurement itself already applies when building a row at
all — kept here too in case a future measurement run lowers its own floor).

Usage::

    uv run scripts/build_relief_paint_csv.py [--min-count 30]
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "docs/evidence/vanilla_paint_vs_relief.csv"
OUT = REPO / "mappings/relief_paint.csv"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-count", type=int, default=30)
    ap.add_argument("--src", type=Path, default=SRC)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args(argv)

    if not args.src.exists():
        raise SystemExit(
            f"{args.src} does not exist; run "
            "scripts/measure_vanilla_relief_paint.py first"
        )

    rows_out = []
    with args.src.open("r", newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            n = int(row.get("n", 0) or 0)
            if n < args.min_count:
                continue
            shares = (row.get("category_shares") or "").strip()
            if not shares:
                continue
            cats = [part.split("=", 1)[0] for part in shares.split(";") if "=" in part]
            if not cats:
                continue
            rows_out.append({
                "ck3_terrain": row["ck3_terrain"],
                "slope_bin": row["slope_bin"],
                "curvature_bin": row["curvature_bin"],
                "elevation_bin": row["elevation_bin"],
                "n": n,
                "category_rank": ";".join(cats),
                "category_shares": shares,
                "top_material": row.get("top_material", ""),
                "top_share": row.get("top_share", ""),
            })

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["# GENERATED by scripts/build_relief_paint_csv.py from "
                     "docs/evidence/vanilla_paint_vs_relief.csv -- do not hand-edit"])
        w.writerow(["ck3_terrain", "slope_bin", "curvature_bin", "elevation_bin",
                     "n", "category_rank", "category_shares", "top_material",
                     "top_share"])
        for r in rows_out:
            w.writerow([r["ck3_terrain"], r["slope_bin"], r["curvature_bin"],
                        r["elevation_bin"], r["n"], r["category_rank"],
                        r["category_shares"], r["top_material"], r["top_share"]])
    print(f"wrote {len(rows_out)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
