#!/usr/bin/env bash
# Regenerate configs/faerun_paint_edges_before.toml: the build-13 paint
# pipeline (hard class edges, noise dither, np.repeat tree blocks), for the
# before/after evidence of lane `paint-edges` (docs/step_map_paint.md §10).
set -euo pipefail
cd "$(dirname "$0")/.."
out=configs/faerun_paint_edges_before.toml
{
  sed -n '1,8p' <<'HDR'
# BEFORE-config for lane `paint-edges`, generated by
# `scripts/make_paint_edges_before_config.sh`: identical to configs/faerun.toml
# except `terrain_paint_soft_edges = false` and `trees_mask_smooth = false`,
# i.e. the build-13 paint pipeline (nearest class edges + a class-agnostic
# noise dither, np.repeat tree blocks). It lives in `configs/` and not in a
# scratch directory because `[map]` relative paths resolve against the config
# file's grandparent (`ck2ck3.map.config.load`: `base = p.parent.parent`), so
# a config outside the repo cannot find `mappings/`.
HDR
  sed -e 's/^terrain_paint_soft_edges = true/terrain_paint_soft_edges = false/' \
      -e 's/^trees_mask_smooth = true/trees_mask_smooth = false/' configs/faerun.toml
} > "$out"
echo "wrote $out"
