#!/usr/bin/env bash
# Regenerate configs/faerun_province_edges_before.toml: the build-15 province
# raster (NEAREST id resize, 2x2 staircase borders), for the before/after
# evidence of lane `province-edges` (docs/step_map_baronies.md §10).
#
# It lives in `configs/` and not in a scratch directory because `[map]`
# relative paths resolve against the config file's grandparent
# (`ck2ck3.map.config.load`: `base = p.parent.parent`), so a config outside
# the repo cannot find `mappings/`.
set -euo pipefail
cd "$(dirname "$0")/.."
out=configs/faerun_province_edges_before.toml
{
  cat <<'HDR'
# BEFORE-config for lane `province-edges`, generated by
# `scripts/make_province_edges_before_config.sh`: identical to
# configs/faerun.toml except `smooth_edges = false`, i.e. the build-15
# NEAREST id resize. Do not hand-edit.
HDR
  sed -e 's/^smooth_edges = true/smooth_edges = false/' configs/faerun.toml
} > "$out"
echo "wrote $out"
