#!/usr/bin/env python
"""How much the CK2 province-history `terrain = X` override moves the map.

Runs the real `map` pipeline twice over the real CK2 mod, text files only
(`skip_images=True`, ~25 s each): once with `[map] province_terrain_history`
off (the pre-lane behaviour, bitmap majority alone) and once on.  Reports:

* the per-barony agreement the application rule was chosen from — for the
  counties that carry an override, how often the bitmap majority of the
  county-CAPITAL barony, and of ALL its baronies, already equals the override;
* what the rule then did: applied / kept-bitmap / already-agreed / unmapped;
* the `common/province_terrain` histogram before and after;
* how many canvas pixels change terrain CLASS, which is what the heightmap
  detail pass and the tree scatter read (`ck2ck3.map.build._terrain_code_grid`).

    PYTHONPATH=$PWD/src uv run python scripts/measure_terrain_history_effect.py \
        --config configs/faerun.toml \
        --out docs/evidence/terrain_history_effect.md
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import replace
from pathlib import Path

from ck2ck3.config import Config
from ck2ck3.map import build as map_build
from ck2ck3.map import terrain_history
from ck2ck3.map.sink import DirectorySink
from ck2ck3.steps import map as map_step

REPO = Path(__file__).resolve().parents[1]


def _run(cfg, tmp: Path, *, skip_images: bool = True):
    sink = DirectorySink(tmp, dry_run=True, verbose=False)
    return map_build.run(cfg, sink, skip_images=skip_images)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default="configs/faerun.toml")
    ap.add_argument("--out", default="docs/evidence/terrain_history_effect.md")
    ap.add_argument(
        "--images",
        action="store_true",
        help=(
            "also run the image passes, so the tree-scatter delta is measured "
            "(the tree pass only runs when images are on). ~2x slower."
        ),
    )
    args = ap.parse_args()

    cfg_cli = Config.load(Path(args.config))

    class Ctx:
        config = cfg_cli
        dry_run = True

        def ck2(self, *parts):
            return (REPO / cfg_cli.ck2_mod).joinpath(*parts)

        def ck3(self, *parts):
            return cfg_cli.ck3_game.joinpath(*parts)

    cfg_on = map_step._map_config(Ctx())
    cfg_off = replace(cfg_on, terrain_history=False)

    tmp = Path("/tmp/terrain_history_effect")
    tmp.mkdir(parents=True, exist_ok=True)
    print("run 1/2: province_terrain_history = false")
    rep_off = _run(cfg_off, tmp, skip_images=not args.images)
    print("run 2/2: province_terrain_history = true")
    rep_on = _run(cfg_on, tmp, skip_images=not args.images)

    rows = _parse_rows(rep_on["_evidence"]["terrain_history_baronies.csv"])
    rules = terrain_history.read_rules(_repo(cfg_on.terrain_history_csv))

    # ------------------------------------------- agreement, per county/barony
    by_county: dict[int, list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        by_county[int(r["ck2_province"])].append(r)

    applied_counties = {
        pid: rs
        for pid, rs in by_county.items()
        if rules.get(rs[0]["ck2_history_terrain"], None)
        and rules[rs[0]["ck2_history_terrain"]].applies
    }
    cap_agree = 0
    all_agree = 0
    any_agree = 0
    n_bar = 0
    bar_agree = 0
    for rs in applied_counties.values():
        want = rules[rs[0]["ck2_history_terrain"]].ck3_terrain
        caps = [r for r in rs if r["is_capital"] == "yes"]
        cap_agree += bool(caps) and caps[0]["bitmap_ck3_terrain"] == want
        agree = [r for r in rs if r["bitmap_ck3_terrain"] == want]
        all_agree += len(agree) == len(rs)
        any_agree += bool(agree)
        n_bar += len(rs)
        bar_agree += len(agree)

    out: list[str] = []
    A = out.append
    A("# `terrain = X` override vs the `terrain.bmp` majority — measured effect\n\n")
    A(
        f"Generated by `scripts/measure_terrain_history_effect.py` over "
        f"`{args.config}`. Two real `map` runs, "
        f"{'with the image passes' if args.images else 'text files only'}.\n\n"
    )

    n_cty = len(applied_counties)
    A("## 1. Agreement before the rule (counties whose override is `apply`)\n\n")
    A("| question | counties | share |\n|---|---|---|\n")
    A(f"| counties with an applied override | {n_cty} | 100 % |\n")
    A(
        f"| county-CAPITAL barony's bitmap already equals the override | "
        f"{cap_agree} | {100 * cap_agree / max(1, n_cty):.1f} % |\n"
    )
    A(
        f"| ALL the county's baronies already equal it | {all_agree} | "
        f"{100 * all_agree / max(1, n_cty):.1f} % |\n"
    )
    A(
        f"| at least one barony already equals it | {any_agree} | "
        f"{100 * any_agree / max(1, n_cty):.1f} % |\n"
    )
    A(
        f"\nPer barony: **{bar_agree} of {n_bar}** "
        f"({100 * bar_agree / max(1, n_bar):.1f} %) already agreed.\n"
    )

    A("\n## 2. What the rule did\n\n| outcome | CK3 provinces |\n|---|---|\n")
    summ = rep_on["terrain_history"]
    for k in terrain_history.OUTCOMES:
        if k == "no_override":
            continue
        A(f"| `{k}` | {summ.get(k, 0)} |\n")
    A(f"| **provinces changed** | **{summ['provinces_changed']}** |\n")
    A(f"\nUnmapped categories: `{summ['unmapped_categories'] or 'none'}`.\n")
    A(
        f"\nCanvas pixels whose terrain CLASS moves (what the heightmap detail "
        f"pass and the tree scatter read): "
        f"**{summ['class_grid_pixels_moved']:,}** "
        f"({100 * summ['class_grid_pixels_moved_share']:.2f} % of the canvas).\n"
    )

    A("\n## 3. `common/province_terrain` histogram\n\n")
    A("| CK3 terrain | bitmap only | + history override | delta |\n|---|---|---|---|\n")
    before, after = rep_off["terrain"], rep_on["terrain"]
    for key in sorted(set(before) | set(after), key=lambda k: -after.get(k, 0)):
        b, a = before.get(key, 0), after.get(key, 0)
        A(f"| `{key}` | {b} | {a} | {a - b:+d} |\n")

    if rep_on.get("trees") and rep_off.get("trees"):
        A("\n## 3b. Tree scatter (the other per-province consumer)\n\n")
        A("| quantity | bitmap only | + history override | delta |\n|---|---|---|---|\n")
        for k in ("placed", "dropped_no_mesh"):
            b, a = rep_off["trees"].get(k, 0), rep_on["trees"].get(k, 0)
            A(f"| `{k}` | {b:,} | {a:,} | {a - b:+,} |\n")
        A(
            "\n`mappings/tree_meshes.csv` gives `farmlands` no mesh, so a "
            "province the author calls farmland loses its canopy - that is "
            "where most of the delta comes from.\n"
        )

    A("\n## 4. Biggest transitions\n\n| from | to | provinces |\n|---|---|---|\n")
    trans = Counter(
        (r["bitmap_ck3_terrain"], r["final_ck3_terrain"])
        for r in rows
        if r["bitmap_ck3_terrain"] != r["final_ck3_terrain"]
    )
    for (a, b), n in trans.most_common(20):
        A(f"| `{a}` | `{b}` | {n} |\n")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("".join(out), encoding="utf-8")
    print("".join(out))
    print(f"wrote {args.out}")
    return 0


def _repo(p: Path) -> Path:
    return p if p.is_absolute() else REPO / p


def _parse_rows(text: str) -> list[dict[str, str]]:
    import csv
    import io

    return list(csv.DictReader(io.StringIO(text)))


if __name__ == "__main__":
    raise SystemExit(main())
