"""Measure vanilla's own whole-map water rasters, so ours can be derived, not guessed.

Three of CK3's map textures are sampled with a **whole-map UV** — the shader
divides the world position by the map size, so every texel is pinned to one
spot of vanilla's Earth (``gfx/FX/jomini/jomini_water_default.fxh:42``).  Ship
none and a custom map draws vanilla's oceans, vanilla's shorelines and
vanilla's climate under its own geography (`docs/step_map_water_border.md`).

To write replacements that look like vanilla rather than like a guess, this
script measures what vanilla itself puts in each of them as a function of two
quantities we can reproduce on any map:

* **distance to the nearest coast**, in texels of the raster itself, and
* **water depth**, from vanilla's own ``map_data/heightmap.png`` against
  ``WATERLEVEL`` (``common/defines/00_defines.txt:77``).

Outputs (one row per bucket, all means over real pixels):

* ``docs/evidence/vanilla_water_by_coast.csv`` — watercolor RGBA and foam-map
  R/G against coast distance, separately for water and land.
* ``docs/evidence/vanilla_water_by_depth.csv`` — watercolor RGBA against depth.
* ``docs/evidence/vanilla_water_summary.csv`` — the handful of scalars the
  converter actually reads: the shallow and deep water colours, the land fill,
  the flat channels, and the coast-distance e-folding length of the foam ramp.
* ``mappings/water_profile.csv`` — the checked-in, hand-editable table
  ``ck2ck3.map.water`` reads: one row per integer coast distance, in **canvas
  pixels** so it survives a change of raster scale.

Usage::

    uv run scripts/measure_vanilla_water.py [--game DIR] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

Image.MAX_IMAGE_PIXELS = None

#: vanilla `common/defines/00_defines.txt:74-77`
VANILLA_WORLD_EXTENTS_Y = 50
VANILLA_WATERLEVEL = 3

#: the two rasters, relative to the install's `game/` dir
WATERCOLOR = "gfx/map/water/watercolor_rgb_waterspec_a.dds"
FOAM_MAP = "gfx/map/water/foam_map.dds"
HEIGHTMAP = "map_data/heightmap.png"

#: coast-distance buckets, in raster texels (upper bound exclusive)
COAST_EDGES = (0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 10**9)
#: depth buckets, in 16-bit heightmap levels below the water surface
DEPTH_EDGES = (0, 50, 200, 500, 1000, 2000, 3000, 3800, 10**9)

#: how far the per-texel profile runs, in texels, into the water and the land
PROFILE_WATER_TEXELS = 128
PROFILE_LAND_TEXELS = 64
#: vanilla's rasters are 4608x2304 against a 9216x4608 canvas
VANILLA_PX_PER_TEXEL = 2

PROFILE_CSV = Path("mappings/water_profile.csv")

PROFILE_HEADER = """\
# GENERATED by scripts/measure_vanilla_water.py from vanilla's own
# gfx/map/water/watercolor_rgb_waterspec_a.dds and foam_map.dds. Checked in and
# hand-editable, like mappings/terrain_paint.csv and mappings/colormap_tints.csv.
#
# Both rasters are sampled by the water shader with a whole-map UV
# (gfx/FX/jomini/jomini_water_default.fxh:42), so a mod that ships neither draws
# vanilla's Earth oceans under its own map. ck2ck3.map.water paints them from
# this profile instead, indexed by each pixel's own distance to the nearest
# coast.
#
#   zone      water = the pixel is sea/lake, land = it is not
#   depth_px  distance to the nearest coast, in CANVAS pixels (not texels), so
#             the table survives a change of [map] water_scale. Vanilla's own
#             rasters are half-canvas, i.e. 2 canvas px per texel.
#   wc_*      watercolor RGB, plus A = the gloss map (fxh:506)
#   foam_r    foam_map.R; the shader uses 1 - R, so high R = foam (fxh:289)
#   foam_g    foam_map.G, the water mask the approaching-wave pass reads (fxh:275)
#
# foam_map's B (140) and A (255) are constant across vanilla's whole raster and
# are written as constants by ck2ck3.map.water, not from this table.
# The last row of each zone is held for every greater depth.
"""


def water_level_16bit(waterlevel: float = VANILLA_WATERLEVEL,
                      extents_y: float = VANILLA_WORLD_EXTENTS_Y) -> int:
    """``WATERLEVEL / WORLD_EXTENTS_Y * 65535`` — the CLAUDE.md invariant."""
    return int(round(waterlevel / extents_y * 65535))


def decimate_to(arr: np.ndarray, shape: tuple[int, int]) -> np.ndarray:
    """Point-sample ``arr`` down to ``shape``; both vanilla rasters divide evenly."""
    fy = arr.shape[0] // shape[0]
    fx = arr.shape[1] // shape[1]
    if fy < 1 or fx < 1:
        raise ValueError(f"{arr.shape} is smaller than {shape}")
    return arr[::fy, ::fx][: shape[0], : shape[1]]


def bucket_rows(values: dict[str, np.ndarray], key: np.ndarray,
                edges: tuple[int, ...], mask: np.ndarray,
                label: str) -> list[dict[str, object]]:
    """Mean of every ``values`` channel per ``key`` bucket, over ``mask``."""
    rows: list[dict[str, object]] = []
    for lo, hi in zip(edges, edges[1:]):
        sel = mask & (key >= lo) & (key < hi)
        n = int(sel.sum())
        if n == 0:
            continue
        row: dict[str, object] = {"zone": label, "lo": lo,
                                  "hi": hi if hi < 10**9 else "", "n": n}
        for name, arr in values.items():
            row[name] = round(float(arr[sel].mean()), 2)
        rows.append(row)
    return rows


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"{len(rows)} rows -> {path}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--game", type=Path,
                    default=Path("../claudespace/game_files"))
    ap.add_argument("--out-dir", type=Path, default=Path("docs/evidence"))
    args = ap.parse_args(argv)

    wc = np.asarray(Image.open(args.game / WATERCOLOR)).astype(np.float32)
    foam = np.asarray(Image.open(args.game / FOAM_MAP)).astype(np.float32)
    h, w = wc.shape[:2]
    if foam.shape[:2] != (h, w):
        raise SystemExit(f"watercolor {w}x{h} != foam {foam.shape[1]}x{foam.shape[0]}")

    heights = decimate_to(np.asarray(Image.open(args.game / HEIGHTMAP)), (h, w))
    level = water_level_16bit()
    water = heights <= level
    depth = np.clip(level - heights.astype(np.int32), 0, None)

    # distance to the nearest pixel of the other class, in raster texels
    d_from_land = ndimage.distance_transform_edt(water)
    d_from_water = ndimage.distance_transform_edt(~water)
    coast = np.where(water, d_from_land, d_from_water)

    channels = {
        "wc_r": wc[..., 0], "wc_g": wc[..., 1], "wc_b": wc[..., 2],
        "wc_a": wc[..., 3],
        "foam_r": foam[..., 0], "foam_g": foam[..., 1],
        "foam_b": foam[..., 2], "foam_a": foam[..., 3],
    }

    by_coast = (bucket_rows(channels, coast, COAST_EDGES, water, "water")
                + bucket_rows(channels, coast, COAST_EDGES, ~water, "land"))
    write_csv(args.out_dir / "vanilla_water_by_coast.csv", by_coast)

    by_depth = bucket_rows(channels, depth, DEPTH_EDGES, water, "water")
    write_csv(args.out_dir / "vanilla_water_by_depth.csv", by_depth)

    shelf = water & (d_from_land <= 8)
    deep = water & (d_from_land > 64)
    land = ~water

    def mean_rgba(mask: np.ndarray, arr: np.ndarray) -> list[int]:
        return [int(round(float(v))) for v in arr[mask].mean(axis=0)]

    summary = [
        {"quantity": "raster_width", "value": w,
         "note": f"vanilla ships both rasters at {w}x{h}, half the 9216x4608 canvas"},
        {"quantity": "raster_height", "value": h, "note": ""},
        {"quantity": "water_level_16bit", "value": level,
         "note": "WATERLEVEL 3 / WORLD_EXTENTS_Y 50 * 65535"},
        {"quantity": "water_fraction", "value": round(float(water.mean()), 4),
         "note": "share of vanilla's map that is below the water surface"},
    ]
    for name, mask, note in (
        ("watercolor_shelf", shelf, "water within 8 texels of a coast"),
        ("watercolor_deep", deep, "water more than 64 texels from a coast"),
        ("watercolor_land", land, "land; rivers sample these texels"),
    ):
        r, g, b, a = mean_rgba(mask, wc)
        summary += [
            {"quantity": f"{name}_r", "value": r, "note": note},
            {"quantity": f"{name}_g", "value": g, "note": ""},
            {"quantity": f"{name}_b", "value": b, "note": ""},
            {"quantity": f"{name}_a", "value": a, "note": "alpha = gloss"},
        ]
    fr_shore = float(foam[..., 0][water & (d_from_land <= 2)].mean())
    fr_deep = float(foam[..., 0][deep].mean())
    # e-folding length of (foam_r - deep) against coast distance, over water
    sel = water & (d_from_land <= 64) & (d_from_land >= 1)
    y = foam[..., 0][sel] - fr_deep
    x = d_from_land[sel]
    ok = y > 1
    tau = float(-1.0 / np.polyfit(x[ok], np.log(y[ok]), 1)[0]) if ok.any() else 0.0
    summary += [
        {"quantity": "foam_r_shore", "value": round(fr_shore, 1),
         "note": "foam_map.R within 2 texels of a coast; shader uses 1 - R"},
        {"quantity": "foam_r_deep", "value": round(fr_deep, 1),
         "note": "foam_map.R more than 64 texels out"},
        {"quantity": "foam_r_tau_texels", "value": round(tau, 2),
         "note": "e-folding coast distance of the foam ramp, raster texels"},
        {"quantity": "foam_g_water", "value": int(round(float(foam[..., 1][water].mean()))),
         "note": "foam_map.G is the water mask the approaching-wave pass reads"},
        {"quantity": "foam_g_land", "value": int(round(float(foam[..., 1][land].mean()))),
         "note": ""},
        {"quantity": "foam_b_const", "value": int(np.unique(foam[..., 2])[0])
         if np.unique(foam[..., 2]).size == 1 else "varies", "note": "constant in vanilla"},
        {"quantity": "foam_a_const", "value": int(np.unique(foam[..., 3])[0])
         if np.unique(foam[..., 3]).size == 1 else "varies", "note": "constant in vanilla"},
    ]
    write_csv(args.out_dir / "vanilla_water_summary.csv", summary)
    for row in summary:
        print(f"  {row['quantity']:<24} {row['value']}")

    write_profile(PROFILE_CSV, channels, d_from_land, d_from_water, water)
    return 0


def write_profile(path: Path, channels: dict[str, np.ndarray],
                  d_from_land: np.ndarray, d_from_water: np.ndarray,
                  water: np.ndarray) -> None:
    """One row per integer coast distance: the table the converter reads.

    Depth is written in canvas pixels rather than texels so a change of
    ``[map] water_scale`` does not silently rescale the whole coastline.
    """
    fields = ["zone", "depth_px", "n", "wc_r", "wc_g", "wc_b", "wc_a",
              "foam_r", "foam_g"]
    rows: list[dict[str, object]] = []
    for zone, dist, mask, limit in (
        ("water", d_from_land, water, PROFILE_WATER_TEXELS),
        ("land", d_from_water, ~water, PROFILE_LAND_TEXELS),
    ):
        # distance_transform_edt gives 0 only outside the mask, so the first
        # texel of each zone is at distance 1.
        rounded = np.rint(dist).astype(np.int32)
        for texel in range(1, limit + 1):
            sel = mask & (rounded == texel)
            n = int(sel.sum())
            if n < 100:
                continue
            row: dict[str, object] = {
                "zone": zone,
                "depth_px": texel * VANILLA_PX_PER_TEXEL,
                "n": n,
            }
            for name in fields[3:]:
                row[name] = int(round(float(channels[name][sel].mean())))
            rows.append(row)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        fh.write(PROFILE_HEADER)
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    print(f"{len(rows)} rows -> {path}")


if __name__ == "__main__":
    raise SystemExit(main())
