"""Measure how far each CK3 locator type sits from the settlement, in vanilla.

Lane `map-assets`.  A `siege` marker is the army *besieging the settlement*, a
unit stack is the army *standing at* it: vanilla does not scatter these across
the province, it clusters them a few pixels around the holding model.  So the
right shape for a generated map is **one anchor per province plus a small
per-type offset**, not one independent point per type.

This script produces that offset table from the only authority there is —
CK3 1.19's own `gfx/map/map_object_data/*_locators.txt` — by taking, for every
province id vanilla defines in `building_locators.txt`, the vector from the
`buildings` instance to the same id's instance in every other file.  It writes
`mappings/locator_offsets.csv`, which `ck2ck3.map.locators` reads.

Frame: `position = { x  y  z }` in provinces.png pixels with **z bottom-up**
(`docs/evidence/locator_frame.md`), so `dz > 0` means *north*.  The converter
turns that into a top-down pixel offset itself.

Run::

    uv run scripts/measure_vanilla_locator_offsets.py [--game DIR] [--out FILE]
"""

from __future__ import annotations

import argparse
import re
import statistics
from pathlib import Path

DEFAULT_GAME = Path(
    "/home/cvdbdo/.local/share/Steam/steamapps/common/Crusader Kings III/game"
)

#: `name=` -> file, every per-province locator vanilla 1.19 ships.
#: `buildings` is the anchor and is measured against itself (0, 0).
LOCATORS = {
    "buildings": "building_locators.txt",
    "special_building": "special_building_locators.txt",
    "siege": "siege_locators.txt",
    "activities": "activities.txt",
    "unit_stack_player_owned": "player_stack_locators.txt",
    "unit_stack_other_owner": "other_stack_locators.txt",
    "combat": "combat_locators.txt",
}

_INSTANCE = re.compile(
    r"id\s*=\s*(\d+)\s*"
    r"position\s*=\s*\{\s*([-\d.eE]+)\s+([-\d.eE]+)\s+([-\d.eE]+)\s*\}"
)

HEADER = """\
# locator,dx_px,dz_px,median_dist_px,p95_dist_px,dx_q1,dx_q3,dz_q1,dz_q3,instances
#
# GENERATED by scripts/measure_vanilla_locator_offsets.py. Do not hand-edit;
# re-run the script instead. Every reader must skip these '#' lines.
#
# Offset of each CK3 locator type from the SAME province's `buildings`
# instance, measured over CK3 1.19's own gfx/map/map_object_data files.
# Units are vanilla provinces.png pixels; `dz` is BOTTOM-UP (dz > 0 = north),
# the frame the locator files themselves use (docs/evidence/locator_frame.md).
# dx/dz are medians; q1/q3 are the interquartile range of the same sample.
#
# Why this table exists: a siege marker is the army besieging the settlement
# and a unit stack is the army standing at it, so vanilla clusters every type
# within ~15 px of the holding model rather than scattering them across the
# province. `ck2ck3.map.locators` reproduces that by placing ONE anchor per
# province (the CK2 positions.txt slot-0 town for a county capital, the
# province centroid otherwise) and adding these offsets to it.
# docs/step_map_assets.md.
"""


def read_instances(path: Path) -> dict[int, tuple[float, float, float]]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    return {
        int(m.group(1)): (float(m.group(2)), float(m.group(3)), float(m.group(4)))
        for m in _INSTANCE.finditer(text)
    }


def quartiles(values: list[float]) -> tuple[float, float]:
    if len(values) < 4:
        return (min(values, default=0.0), max(values, default=0.0))
    q = statistics.quantiles(values, n=4)
    return (q[0], q[2])


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", type=Path, default=DEFAULT_GAME)
    ap.add_argument("--out", type=Path, default=Path("mappings/locator_offsets.csv"))
    args = ap.parse_args(argv)

    src = args.game / "gfx" / "map" / "map_object_data"
    base = read_instances(src / LOCATORS["buildings"])
    if not base:
        print(f"no vanilla locators at {src}")
        return 1
    print(f"{len(base)} vanilla `buildings` instances at {src}")

    rows = []
    for name, fname in LOCATORS.items():
        inst = read_instances(src / fname)
        dxs, dzs, dists = [], [], []
        for pid, v in inst.items():
            b = base.get(pid)
            if b is None or pid == 0:
                continue
            dx, dz = v[0] - b[0], v[2] - b[2]
            dxs.append(dx)
            dzs.append(dz)
            dists.append((dx * dx + dz * dz) ** 0.5)
        if not dxs:
            print(f"  {name:26} no shared ids, skipped")
            continue
        dx_q1, dx_q3 = quartiles(dxs)
        dz_q1, dz_q3 = quartiles(dzs)
        p95 = sorted(dists)[int(0.95 * (len(dists) - 1))]
        row = {
            "locator": name,
            "dx_px": round(statistics.median(dxs), 3),
            "dz_px": round(statistics.median(dzs), 3),
            "median_dist_px": round(statistics.median(dists), 3),
            "p95_dist_px": round(p95, 3),
            "dx_q1": round(dx_q1, 3),
            "dx_q3": round(dx_q3, 3),
            "dz_q1": round(dz_q1, 3),
            "dz_q3": round(dz_q3, 3),
            "instances": len(dxs),
        }
        rows.append(row)
        print(
            f"  {name:26} n={len(dxs):>6}  dx {row['dx_px']:+7.2f} "
            f"[{row['dx_q1']:+6.2f},{row['dx_q3']:+6.2f}]  "
            f"dz {row['dz_px']:+7.2f} [{row['dz_q1']:+6.2f},{row['dz_q3']:+6.2f}]  "
            f"dist median {row['median_dist_px']:6.2f} p95 {row['p95_dist_px']:6.2f}"
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", newline="") as f:
        f.write(HEADER)
        f.write(",".join(rows[0]) + "\n")
        for r in rows:
            f.write(",".join(str(r[k]) for k in rows[0]) + "\n")
    print(f"-> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
