"""Measure the frame vanilla paints around its map, so ours can copy it.

``gfx/map/surround_map/surround_mask.dds`` is sampled with a whole-map UV and
decides three things (`verified`, shader lines quoted in
`docs/step_map_water_border.md` §3):

* ``.b`` — ``pdxterrain.shader:777`` ``SurroundMapAlpha = 1 - mask.b`` makes the
  **terrain itself transparent** on the flat map, and ``pdxborder.shader:115``
  ``clip( 1 - mask.b - 0.1 )`` throws away the political borders there.  B=255
  hides the map, B=0 shows it.
* ``.g`` — ``surroundmap.shader:230`` ``CloudMask``, "don't draw clouds over map".
* ``.r`` — ``surroundmap.shader:352`` the map's drop shadow on the surround plane.

Vanilla's own mask is hand-painted around **Earth's** coastline: at the top it
eats up to 67 % of the map height, which is empty Arctic there and real
territory on any other map.  Copying the *file* is therefore wrong; what we
want is the **thinnest frame vanilla itself uses**, the profile it paints where
its own content runs right up to the edge.

This script extracts exactly that.  For each of the four edges it takes the 5th
percentile of every channel at each inward depth (so a single un-masked ray
does not define the frame, but the Siberia bite does not either), then takes
the element-wise minimum over the four edges.  The result is a 1-D profile,
"channel value at ``d`` texels in from the nearest edge", which
``ck2ck3.map.surround`` applies to all four edges of our own canvas.

Depth is in raster texels.  Vanilla's mask is 4096x2048 against a 9216x4608
canvas and ours is written at half canvas, so a texel is roughly the same
ground distance in both and the profile transfers unscaled (`assumed`; the
exact ratio is 2.25 canvas px per vanilla texel against 2.0 for ours).

Outputs
    docs/evidence/vanilla_surround_edges.csv   per-edge p05 profile
    mappings/surround_profile.csv              the min-of-edges frame we ship

Usage::

    uv run scripts/measure_vanilla_surround.py [--game DIR] [--depth 96]
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

SURROUND_MASK = "gfx/map/surround_map/surround_mask.dds"

REPO = Path(__file__).resolve().parents[1]
EDGES_CSV = REPO / "docs" / "evidence" / "vanilla_surround_edges.csv"
PROFILE_CSV = REPO / "mappings" / "surround_profile.csv"

PROFILE_HEADER = """\
# GENERATED by scripts/measure_vanilla_surround.py from vanilla's own
# gfx/map/surround_map/surround_mask.dds. Checked in and hand-editable, like
# mappings/terrain_paint.csv and mappings/colormap_tints.csv.
#
# One row per texel of depth in from the nearest map edge. The three values are
# the frame vanilla paints where its own content reaches the edge (the
# element-wise minimum, over the four edges, of the 5th-percentile profile) --
# NOT vanilla's actual mask, which is painted around Earth's coastline and hides
# up to 67 % of the map height at the top.
#
#   b  pdxterrain.shader:777  -- 255 hides the terrain on the flat map, 0 shows it
#   g  surroundmap.shader:230 -- cloud mask; clouds are drawn where this is high
#   r  surroundmap.shader:352 -- the map's drop shadow onto the surround plane
#
# ck2ck3.map.surround reads this and paints value(min distance to any edge);
# every depth past the last row is 0 (map fully visible, no clouds, no shadow).
"""


def edge_profiles(mask: np.ndarray, depth: int) -> dict[str, np.ndarray]:
    """``{edge: (depth, 3) p05 profile}`` for the four edges of ``mask``."""
    return {
        "top": np.percentile(mask[:depth, :, :3], 5, axis=1),
        "bottom": np.percentile(mask[: -depth - 1 : -1, :, :3], 5, axis=1),
        "left": np.percentile(np.transpose(mask[:, :depth, :3], (1, 0, 2)), 5, axis=1),
        "right": np.percentile(
            np.transpose(mask[:, : -depth - 1 : -1, :3], (1, 0, 2)), 5, axis=1
        ),
    }


def frame_profile(profiles: dict[str, np.ndarray]) -> np.ndarray:
    """Element-wise minimum over the edges: the thinnest frame vanilla uses."""
    return np.min(np.stack(list(profiles.values())), axis=0)


def trim(profile: np.ndarray) -> np.ndarray:
    """Drop the all-zero tail; the writer treats anything past it as zero."""
    nonzero = np.nonzero(profile.max(axis=1))[0]
    return profile[: int(nonzero[-1]) + 1] if nonzero.size else profile[:1]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--game", type=Path,
                    default=Path("../claudespace/game_files"))
    ap.add_argument("--depth", type=int, default=96,
                    help="how far in from each edge to look, in texels")
    args = ap.parse_args(argv)

    mask = np.asarray(Image.open(args.game / SURROUND_MASK)).astype(np.float32)
    h, w = mask.shape[:2]
    print(f"{args.game / SURROUND_MASK}  {w}x{h}")

    profiles = edge_profiles(mask, args.depth)
    rows = [
        {"edge": edge, "depth": d,
         "r": round(float(p[d, 0]), 1),
         "g": round(float(p[d, 1]), 1),
         "b": round(float(p[d, 2]), 1)}
        for edge, p in profiles.items()
        for d in range(args.depth)
    ]
    EDGES_CSV.parent.mkdir(parents=True, exist_ok=True)
    with EDGES_CSV.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["edge", "depth", "r", "g", "b"])
        writer.writeheader()
        writer.writerows(rows)
    print(f"{len(rows)} rows -> {EDGES_CSV}")

    frame = trim(frame_profile(profiles))
    PROFILE_CSV.parent.mkdir(parents=True, exist_ok=True)
    with PROFILE_CSV.open("w", newline="", encoding="utf-8") as fh:
        fh.write(PROFILE_HEADER)
        writer = csv.DictWriter(fh, fieldnames=["depth", "r", "g", "b"])
        writer.writeheader()
        for d, (r, g, b) in enumerate(frame):
            writer.writerow({"depth": d, "r": int(round(r)),
                             "g": int(round(g)), "b": int(round(b))})
    print(f"{len(frame)} depths -> {PROFILE_CSV}")

    def first_zero(channel: int) -> int:
        z = np.nonzero(frame[:, channel] <= 0)[0]
        return int(z[0]) if z.size else len(frame)

    print(f"  frame depth: b {first_zero(2)} texels, g {first_zero(1)}, "
          f"r {first_zero(0)} (total {len(frame)})")
    for d in range(0, len(frame), 4):
        r, g, b = frame[d]
        print(f"  {d:3d}: r {r:5.0f}  g {g:5.0f}  b {b:5.0f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
