#!/usr/bin/env bash
# Validate the characters/dynasties lane's output with ck3-tiger.
#
# Builds a throwaway mod in a scratch folder (only this lane's OUTPUTS plus a
# descriptor) and runs ck3-tiger against the CK3 1.19 install, writing the
# report to docs/evidence/tiger_characters.txt.
#
# GOTCHA (docs/formats_characters.md ss10): ck3-tiger 1.19.0 PANICS
# (index out of bounds, src/trigger.rs:1454) when one mod ships both the
# generated history/characters and any localization/. Each subtree alone
# validates fine, so this runs one pass per subtree and one combined pass, and
# records whatever each produces. scripts/bisect_tiger_panic.py narrows the
# panic.
#
# Usage: scripts/tiger_characters.sh [scratch_dir]
set -uo pipefail
cd "$(dirname "$0")/.."
REPO="$PWD"
SCRATCH="${1:-${TMPDIR:-/tmp}/ck2ck3-tiger-characters}"
GAME="${CK3_GAME:-$HOME/.local/share/Steam/steamapps/common/Crusader Kings III}"
REPORT="$REPO/docs/evidence/tiger_characters.txt"

command -v ck3-tiger >/dev/null || { echo "ck3-tiger not on PATH"; exit 2; }
# --game wants the INSTALL ROOT, not the game/ subfolder.
[ -d "$GAME/game" ] || { echo "CK3 game files not under $GAME/game (set CK3_GAME)"; exit 2; }

BUILD="$SCRATCH/build"
rm -rf "$SCRATCH"; mkdir -p "$BUILD"
uv run ck2ck3 --config configs/faerun.toml \
  --steps dynasties,characters --out "$BUILD" --no-evidence >/dev/null 2>&1

# One pass per subtree, plus the combined mod. `replace_path` is deliberately
# omitted: ck3-tiger rejects `replace_path = history` outright, and the lane is
# validating its own files, not the mod's load order.
pass() {
  local name="$1"; shift
  local dir="$SCRATCH/$name"
  rm -rf "$dir"; mkdir -p "$dir"
  for sub in "$@"; do
    [ -e "$BUILD/$sub" ] || continue
    mkdir -p "$dir/$(dirname "$sub")"
    cp -r "$BUILD/$sub" "$dir/$(dirname "$sub")/"
  done
  {
    printf 'version="0.1.0"\n'
    printf 'tags={\n\t"Total Conversion"\n}\n'
    printf 'name="ck2ck3 characters lane - %s"\n' "$name"
    printf 'supported_version="1.19.*"\n'
    printf 'path="%s"\n' "$dir"
  } > "$dir.mod"

  echo "===== pass: $name ($*)"
  ck3-tiger --game "$GAME" "$dir.mod" 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > "$dir.log"
  tail -1 "$dir.log"
  echo
  echo "-- by kind"
  grep -oE '^(error|warning|untidy|tips)\([a-z-]+\)' "$dir.log" | sort | uniq -c | sort -rn
  echo "-- missing-item, by subject"
  grep -oE '^error\(missing-item\): [a-z_ ]+' "$dir.log" \
    | sed 's/.*: //' | awk '{print $1}' | sort | uniq -c | sort -rn
  echo "-- one example per message (message text only, ids stripped)"
  grep -oE '^(error|warning|untidy)\([a-z-]+\): .*' "$dir.log" \
    | sed 's/`[^`]*`/X/g; s/fae_[0-9a-z_]*/ID/g; s/[0-9]\+\.[0-9]\+\.[0-9]\+/DATE/g' \
    | sed -E "s/(for name|key|culture|trait|faith|title|modifier) [^ ]+$/\\1 X/" \
    | sort | uniq -c | sort -rn | head -40
  echo
  echo "full log: $dir.log"
  echo
}

{
  echo "# ck3-tiger report - lane characters"
  echo "# generated by scripts/tiger_characters.sh on $(date -Is)"
  echo "# game: $GAME"
  echo "# tiger: $(ck3-tiger --version 2>&1 | head -1)"
  echo "#"
  echo "# Summaries only. Full per-pass logs: $SCRATCH/<pass>.log"
  echo "# Expected remaining errors are other lanes' ids: culture and faith"
  echo "# (cultures-religions), trait (traits), title (titles-history),"
  echo "# modifier (modifiers). See docs/step_characters.md."
  echo
  pass dynasties  common/dynasties
  pass loc        localization/english
  pass characters history/characters
  pass all        common/dynasties localization/english history/characters
} > "$REPORT" 2>&1

# The report is a committed summary; the full per-pass logs stay in $SCRATCH,
# because one combined pass alone is 437k lines.
echo "report: $REPORT ($(wc -l < "$REPORT") lines)"
grep -E '^(=====|fatal:)' "$REPORT" | sed 's/^/  /'
